### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by simaxme** [cweijan/vscode-office#1]
Hi, at first i want to thank you for this ingenious extension. But I personally have one improvement tip: please introduce a dark mode if it's possible. I am very used to it in VSCode.

**Comment by shit-hub** [comment]
I have a configure, maybe you can have a try.
When I config the extension as following, then the extension can open in dark mode. 
```json
"vscode-office.autoTheme": true
```
or choose "Viewer follow vscode theme" option in the extention config page

**Comment by simaxme** [comment]
Unfortunately it doesn't work as you see in the screenshot.
![Bildschirmfoto vom 2021-04-06 19-50-15](https://user-images.githubusercontent.com/59118411/113756355-9087f700-9711-11eb-84c0-e9643391a1b6.png)

**Comment by shit-hub** [comment]
Oh, It maybe just work on markdown editer
![image](https://user-images.githubusercontent.com/63307843/113795299-20b05580-977f-11eb-8c55-c5e4742abb64.png)
And I try to open other file in my environment, svg and docx file can also support dark mode. but execl file not support

**Comment by RayyanNafees** [comment]
All you've to do is to open the settings of the extension and enable auto theme, as in here
![image](https://user-images.githubusercontent.com/59685062/117570922-0e149d80-b0ea-11eb-913b-f7a7fcf0dfb5.png)

the result
![image](https://user-images.githubusercontent.com/59685062/117570939-1d93e680-b0ea-11eb-94ea-316f901044e5.png)
...just that i don't know how to edit its language from chinese...

**Comment by youralmight** [comment]
I tried it with the extension theme `Atom One Dark` and it worked perfectly.

**Comment by cweijan** [comment]
It has been optimized in the latest version.

**Comment by rickythefox** [comment]
<img width="299" alt="Image" src="https://github.com/user-attachments/assets/e26cf82d-8ed3-42e5-bb82-69a7651aab1c" />

Still broken?
