### ISSUE TITLE
HyperMD编辑器的样式文件是哪个？

### ISSUE THREAD

**Issue by jxjxjhjh** [cweijan/vscode-office#10]
https://laobubu.net/HyperMD/#./docs/zh-CN/README.md

**Comment by cweijan** [comment]
大概在后天会更新成vditor, hyperMD要移除掉了, 到时候再看看.

**Comment by cweijan** [comment]
版本1.8.2更新了, 同时加了个测试主题, 打开设置后勾选设置项试用.
![image](https://user-images.githubusercontent.com/27798227/100685098-a594f800-33b6-11eb-8aab-da69202912e4.png)
