### ISSUE TITLE
分割线无法正常渲染展示

### ISSUE THREAD

**Issue by diduweiwu** [cweijan/vscode-office#101]
使用三个横岗回车后,分割线是正常添加进去了,也有占位的效果,但视觉上看不出来.已经切换了IDE的很多Color theme,都一样的情况.去vditor的demo试了下是正常的.
还有个是EMOJ列表是空白的,不知道我是不是有什么组件没安装还是没配置好,不过我很少用E
![iShot_2022-07-22_10 43 55](https://user-images.githubusercontent.com/6733790/180354847-12f1a189-3628-48db-931c-ad0958297504.gif)
MOJ影响不大.
麻烦大佬空了验证修复下分割线的问题~

**Comment by cweijan** [comment]
我一直用分割线都是正常的, 换了几个主题也可以, 你用的扩展是typora还是office viewer, 
![image](https://user-images.githubusercontent.com/27798227/180362731-ead50e2c-d064-4504-bdf1-1879b2efc769.png)

**Comment by diduweiwu** [comment]
> 我一直用分割线都是正常的, 换了几个主题也可以, 你用的扩展是typora还是office viewer, ![image](https://user-images.githubusercontent.com/27798227/180362731-ead50e2c-d064-4504-bdf1-1879b2efc769.png)

用的是office viewer,刚试了下，windows10上面新安装的vscode使用插件也会有横杠问题。。。。

**Comment by diduweiwu** [comment]
额老哥,不是H1 H2的那个分割线哦,是输入 ---  回车后那个分割线

**Comment by cweijan** [comment]
Hi, 在2.6.7版本修复了.
