### ISSUE TITLE
markdown的工具栏能否加一个刷新（重新渲染）的按钮

### ISSUE THREAD

**Issue by rayenyang** [cweijan/vscode-office#103]
好像之前是有的？现在找不到了。

当引用的外部资源，例如图片，内容发生变化时，现在需要关闭文件然后重新打开，不太方便

**Comment by rayenyang** [comment]
可以通过vscode快捷键刷新

**Comment by cweijan** [comment]
由于vscode的缓存机制, 重新加载也不行, 只能关闭重新打开.
