### ISSUE TITLE
latex 公式预览不完整

### ISSUE THREAD

**Issue by qxuan512** [cweijan/vscode-office#106]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/38425605/182012698-46b26616-fd9e-4597-9d0f-7be09a9f9be9.png">

\begin{aligned}
&[\theta_{11},\theta_{12}]=\text{softmax}\left(\frac{q_1k^T_1}{\sqrt{d_k}},\quad \frac{q_1k^T_2}{\sqrt{d_k}}\right)\\
&[\theta_{21},\theta_{22}]=\text{softmax}\left(\frac{q_2k^T_1}{\sqrt{d_k}},\quad \frac{q_2k^T_2}{\sqrt{d_k}}\right)
\end{aligned}

**Comment by qxuan512** [comment]
我退回到2.5.6 就正常显示

**Comment by cweijan** [comment]
你试下最新版, 我用你这个公式可以显示.

**Comment by qxuan512** [comment]
> 



> 你试下最新版, 我用你这个公式可以显示.

我试了，还是不行。。。

**Comment by Jeremy-Shang** [comment]
我也有同样的问题，貌似公式只要是两层以上就显示不完全，插件版本是最新的。macOS12.5.1

**Comment by Jeremy-Shang** [comment]
<img width="621" alt="Screen Shot 2022-09-02 at 19 00 47" src="https://user-images.githubusercontent.com/47731385/188125922-b620a140-6027-4f97-a67d-b963cc2e528a.png">

**Comment by cweijan** [comment]
试下刚发布的2.7.0, 升级了vditor的版本.

**Comment by clq9920** [comment]
> 试下刚发布的2.7.0, 升级了vditor的版本.

还是不行
![image](https://user-images.githubusercontent.com/48880318/188295889-c6f2daa6-313d-4fec-9881-8aec2ff0e867.png)

**Comment by clq9920** [comment]
有对vditor的配置文件吗,使用的是katex?

**Comment by Jeremy-Shang** [comment]
版本2.7.1， math渲染为katex，但是好像还是不行，用vscode-all-markdown插件就可以成功显示。是不是我存在什么配置错误
![image](https://user-images.githubusercontent.com/47731385/190168131-45cb011b-bac5-4ab2-8002-0bd0e0ea817f.png)

**Comment by Jeremy-Shang** [comment]
找到问题了，在color theme的设置中。如果不跟随系统选择，它默认的白背景可以成功显示多行的公式，但是深色背景就不行。希望开发者可以针对这个修复一下～～
![image](https://user-images.githubusercontent.com/47731385/190169372-0954f667-2cfb-446f-bfdd-69b509ea3151.png)

**Comment by cweijan** [comment]
已发布2.7.2修复.
