### ISSUE TITLE
DOCX与PPTX支持

### ISSUE THREAD

**Issue by xingyuqi** [cweijan/vscode-office#107]
能否恢复DOCX的支持？ 除了MD，工作中还是不可避免要接触很多DOCX文件。非常感谢。

此外，是否有计划支持PPTX？

**Comment by cweijan** [comment]
docx已经恢复支持很久了, 你用的是offview viewer吗.. 
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office
pptx没法支持, 没有开源的解析库.

**Comment by xingyuqi** [comment]
你好，我注意到问题所在了，因为我有一部分是DOC的，插件不支持DOC。，所以就有这个问题

**Comment by cweijan** [comment]
是的, doc没办法支持, 它的格式是二进制的, 而docx是xml.

**Comment by cweijan** [comment]
PPTX已在版本4.0.0支持
