### ISSUE TITLE
How do I change the name of the image folder

### ISSUE THREAD

**Issue by DennisL68** [cweijan/vscode-office#109]
I would like to user the folder name `.image` instead of `image` when pasting images to make it invisible from Wiki navigation menus such as in Azure DevOps.

What's the setting and syntax for that in settings.json?

**Comment by cweijan** [comment]
Hi, there is an option to modify it.
![image](https://user-images.githubusercontent.com/27798227/183937975-0bae2845-87f8-4c3a-a308-8a32bd0d2c4b.png)

**Comment by DennisL68** [comment]
The setting isn't present in older versions of the extension.

**Comment by cweijan** [comment]
@DennisL68  Why don't you use the latest version? New features cannot exist in older versions.

**Comment by DennisL68** [comment]
I though I had, since all Extensions in VS Code are supposed to update automatically :)
I did a manual re-install instead as soon as I noticed this.
