### ISSUE TITLE
编辑之后得到的内容不是markdown的文本，而是一大堆数字

### ISSUE THREAD

**Issue by kaldr** [cweijan/vscode-office#11]
Office Viewer更新以后，体验更棒了，但是遗憾的是编辑完成之后，得到的内容是一大串数字。

比如我打的内容是：

![CleanShot 2020-12-01 at 20 24 20](https://user-images.githubusercontent.com/1249206/100740162-37cae980-3413-11eb-9e81-5e229d4bad56.png)

实际上下次打开得到的是：

> 160682507480016068250754541606825076149160682507628316068250776621606825077822160682507824316068250782951606825078442160682507854316068250785991606825079080160682507917816068250792881606825079418160682507954516068250798051606825079865160682507994316068250800951606825080201160682508036816068250805141606825080622160682508073016068250808621606825081260160682508144716068250815391606825081662160682508177516068250818321606825082040160682508268116068250828511606825082921160682508305716068250831271606825083188160682508322716068250833121606825083378160682508349016068250838921606825084294160682508473716068250849011606825085047160682508535716068250856611606825086026160682508611516068250862271606825086443160682508654516068250866051606825086806160682508710916068250872611606825087374160682508756016068250875951606825087793160682508788916068250879481606825087994160682508809316068250885681606825089841160682509023016068250903671606825090580160682509076416068250908651606825090993160682509114616068250912151606825091298160682509146016068250915601606825159697

用OfficeViewer和其他工具打开也是这样的：

![CleanShot 2020-12-01 at 20 25 15](https://user-images.githubusercontent.com/1249206/100740249-5d57f300-3413-11eb-818e-d24e090b3c80.png)

**Comment by cweijan** [comment]
2.8.4已修复.
