### ISSUE TITLE
How to add a new column to a table?

### ISSUE THREAD

**Issue by ueliwechsler** [cweijan/vscode-office#11]
Thanks a lot for creating this extension. It is something I was looking for a long time.

Is there a way to add a new column/row to a table, once it was automatically created (without going into the md-"sourcecode")?

**Comment by cweijan** [comment]
I'm not sure you mean him.
![image](https://user-images.githubusercontent.com/27798227/117394176-3eacd980-af28-11eb-89f3-68a353a38c62.png)

**Comment by ueliwechsler** [comment]
I was talking about markdown files.

![image](https://user-images.githubusercontent.com/12156892/117792962-0f5ddb80-b24c-11eb-9418-3422dc21bd5f.png)

Is there a short cut or option to add an additional row inside the office viewer?

**Comment by cweijan** [comment]
Version 2.1.2 has been support.
![image](https://user-images.githubusercontent.com/27798227/120055002-ffc0fe00-c065-11eb-992b-1f16f1dcb6ae.png)

**Comment by illyber** [comment]
![image](https://user-images.githubusercontent.com/65058984/183662567-2ce32149-2196-434d-b90f-68334129f4b8.png)
你好。好像我的表格不会弹出插入行列的菜单。不知道怎么回事。
