### ISSUE TITLE
能否关闭Markdown编辑器中单引号自动补全功能

### ISSUE THREAD

**Issue by qouteall** [cweijan/vscode-office#110]
在使用Markdown编辑器的时候，键入一个单引号`'`会导致它自动添加第二个单引号`'`，在英文中很多地方要用到单独的单引号所以这个功能让人很难受，要手动右移删除一个单引号。这个插件没有找到设置，不知道怎么关闭这个功能。

可以确定这不是vditor的问题，在其demo中 https://ld246.com/guide/markdown 是不会自动补全单引号的

在VSCode中将Auto Closing Quotes设置为never也没有用

**Comment by cweijan** [comment]
Hai, 已经在2.6.7版本关闭
