### ISSUE TITLE
请问如何更改vditor设置

### ISSUE THREAD

**Issue by qouteall** [cweijan/vscode-office#112]
我想关闭代码块的preview，因为相同代码重复两遍很占空间而且容易点错。需要修改options.preview.markdown.codeBlockPreview，但插件设置里没有修改vditor设置的地方

**Comment by qouteall** [comment]
还有需要修改`options.tab`将tab变成4个字符，默认的8字符宽度不好。

**Comment by cweijan** [comment]
Hi, 发布了2.6.7版本, 代码预览现在可以关闭了. 
![image](https://user-images.githubusercontent.com/27798227/187055280-edfd5aff-b599-4fbf-ad49-5d90724de3ac.png)
options.tab改了之后无效, 貌似是以前vditor被我改过的原因, 之前有人也提了issue, 会在那里跟进.

**Comment by zhaoqingqing** [comment]
> 还有需要修改`options.tab`将tab变成4个字符，默认的8字符宽度不好。

options.tab 在那里可以修改？

**Comment by cweijan** [comment]
改设置后是什么效果呢, 我有试过改, 但是没效果呢

**Comment by zhaoqingqing** [comment]
> 改设置后是什么效果呢, 我有试过改, 但是没效果呢

哈哈，作者不知道，我也不知道，搜了下issues没有相关内容
