### ISSUE TITLE
不同程序窗口切换回来之后，回到文件开头

### ISSUE THREAD

**Issue by OnismV** [cweijan/vscode-office#116]
不同程序窗口切换回来之后，没有回到之前查看的位置，而是回到了文件的开头
![image](https://user-images.githubusercontent.com/97080926/187896318-7852ca62-55eb-49b9-9ec7-f34fc8cce7f9.png)
![image](https://user-images.githubusercontent.com/97080926/187896323-7fc41b60-7fe3-4196-baf4-98545d253e62.png)
这两个都试过，都有这个问题

**Comment by cweijan** [comment]
试下最新版本2.7.0, 如果还是不行, 在vscode设置下面的选项.
```json
{
    "window.customMenuBarAltFocus": false
}
```

**Comment by OnismV** [comment]
2.7不行，我还是设置window.customMenuBarAltFocus吧

**Comment by OnismV** [comment]
> 试下最新版本2.7.0, 如果还是不行, 在vscode设置下面的选项.
> 
> ```json
> {
>     "window.customMenuBarAltFocus": false
> }
> ```

2.7不行，我还是设置window.customMenuBarAltFocus吧。
谢谢。

**Comment by OnismV** [comment]
> 试下最新版本2.7.0, 如果还是不行, 在vscode设置下面的选项.
> 
> ```json
> {
>     "window.customMenuBarAltFocus": false
> }
> ```

不对呀，我刚才设置window.customMenuBarAltFocus为false后窗口切换暂时正常了，然后我多重启几次VSCode后不管我这个设置为false还是true都会出现切换窗口后文件回到开头的现象。这是什么Bug😂。

**Comment by cweijan** [comment]
每次切回窗口后聚焦到最后一个有焦点的元素

**Comment by OnismV** [comment]
> 每次切回窗口后聚焦到最后一个有焦点的元素

我明白了，它回到的是光标所在位置

**Comment by OnismV** [comment]
> 每次切回窗口后聚焦到最后一个有焦点的元素

问题解决了。
谢谢。

**Comment by cweijan** [comment]
Hi, 没有焦点的情况下确实体验不好,  我发布了2.7.1版本优化了.

**Comment by OnismV** [comment]
> Hi, 没有焦点的情况下确实体验不好, 我发布了2.7.1版本优化了.

👌

**Comment by zhaoqingqing** [comment]
mark
