### ISSUE TITLE
图片路径里的$fileName可以trim一下，如果有文件名空格的话图片在markdown里无法显示了

### ISSUE THREAD

**Issue by bojun1995** [cweijan/vscode-office#117]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/27986257/189492260-c48d7266-b830-4972-b071-28a4724e9974.png">

像这样

**Comment by xingyuqi** [comment]
同意，我也遇到这个问题。可以trim

**Comment by cweijan** [comment]
已发布2.7.2支持.
