### ISSUE TITLE
复制粘贴网页地址没有自动获取网页名称

### ISSUE THREAD

**Issue by luckycucu** [cweijan/vscode-office#118]
我之前写md文件时复制粘贴网页地址，会自动获取网页名称，感觉挺方便的。后面我换了一台电脑重新安装后发现没有这个功能了，找了设置也没有发现可以设置这个功能。想问一下这个功能如何使用的。

之前
![image](https://user-images.githubusercontent.com/40897539/189601072-148b3f37-b176-47ee-b28f-267383bbfab7.png)

之后
![image](https://user-images.githubusercontent.com/40897539/189601164-5040d046-f14f-4f8e-b625-71a1ba2dc774.png)

**Comment by cweijan** [comment]
你从浏览器复制就有, 直接复制url是没有的

**Comment by Panlq** [comment]
> 你从浏览器复制就有, 直接复制url是没有的

在实时预览过程中，考虑支持下 url to link title or url to linkcard 的功能呀，大佬！
