### ISSUE TITLE
关于定期删除缓存

### ISSUE THREAD

**Issue by zhaoqingqing** [cweijan/vscode-office#119]
README中有这样一段：
> 缓存说明:由于vscode每次加载webview会缓存文件, 这个扩展每次会生成3M多, 建议定期进行清理, 打开缓存路径删除所有文件.

我查看本地的这个目录下有很多个文件夹，有些日期是很早之前的，如果全部删除会不会有什么问题？

不过从现有的文件夹命名来看似乎也不能找到那些目录是这个扩展产生的缓存？

![image](https://user-images.githubusercontent.com/3056814/190315921-67fef341-10ed-475c-81bc-cac3895847d5.png)

**Comment by cweijan** [comment]
是任意扩展创建webview都会生成的缓存(例如markdown preview), 可以全部删除.

**Comment by zhaoqingqing** [comment]
> 是任意扩展创建webview都会生成的缓存(例如markdown preview), 可以全部删除.

ok，我备份一下，然后试试全部删除，用几天看看会不会有问题
