### ISSUE TITLE
pdf bookmark tree font color conflict with background color when in dark mode

### ISSUE THREAD

**Issue by heartacker** [cweijan/vscode-office#12]
![image](https://user-images.githubusercontent.com/1876302/117539715-79a13100-b03e-11eb-9e91-e4b8e30da302.png)

**Comment by heartacker** [comment]
在vscode 插件找到一个vscode-pdf插件。这个插件看起来显示很正常，
不知道office 这个插件是否也可以呢？

下图是vscode-pdf 插件显示效果
![image](https://user-images.githubusercontent.com/1876302/119918987-0e42e300-bf9c-11eb-80d9-d871e78f5bd7.png)

![image](https://user-images.githubusercontent.com/1876302/119918998-126f0080-bf9c-11eb-9d22-a2fadc4a8615.png)

**Comment by heartacker** [comment]
upgrade PDF.js  will fix this issue: https://github.com/James-Yu/LaTeX-Workshop/issues/2640#issuecomment-827366394

**Comment by cweijan** [comment]
已经修复了.
