### ISSUE TITLE
Latex公式在使用`\frac`的时候不显示分母

### ISSUE THREAD

**Issue by hmc123321** [cweijan/vscode-office#120]
Latex公式在使用`\frac`的时候，显示不完全，无论是仅两个字母的短公式或者是从vditor的文档中复制的一大段公式，分母都不能显示。
![image.png](https://s2.loli.net/2022/09/15/NYk7emjyalzVpJM.png)

**Comment by hmc123321** [comment]
找到问题了，使用跟随vscode的默认黑色主题才会这样，取消掉就好了

**Comment by cweijan** [comment]
已发布2.7.2修复.
