### ISSUE TITLE
【功能请求】粘贴时，智能识别网址并产生链接

### ISSUE THREAD

**Issue by grandsong** [cweijan/vscode-office#122]
## 现象

操作如下：

1. 复制一个网址
2. 在编辑器里选中一段文字
3. 粘贴

### 现状

被选中的文字被替换成了网址。

### 期望

被选中的文字变成链接。

## 参考

在“思源笔记”里，就是这样的。

**Comment by cweijan** [comment]
如果你是从浏览器复制的, 就会自动识别, 只有url是不行的, 思源肯定也一样.

**Comment by Panlq** [comment]
<img width="633" height="193" alt="Image" src="https://github.com/user-attachments/assets/e4dc2b06-502d-4b2f-936f-c3cc1e67eaae" />

可以增加这种黏贴自动转标题的功能吗？@cweijan
