### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by talhaayyubi** [cweijan/vscode-office#129]
- Issue Type: `Performance`
- Extension Name: `vscode-office`
- Extension Version: `2.7.1`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.71.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/ARC/AppData/Local/Temp/cweijan.vscode-office-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by cweijan** [comment]
This is caused by the extension automatically cleaning the cache.
