### ISSUE TITLE
How to change language from Chinese?

### ISSUE THREAD

**Issue by RayyanNafees** [cweijan/vscode-office#13]
Beside lving next to China, We indains and so do many other ppl can't get the labels of this extension because they aren't in English. Anyway i could change it to English ?
It's a very powerful and handy extension but because we don't get chinese many ppl are unable to use it.
Plz add english language feature or if it is already plz tell how to enable it.
I can do Enlish scripting for u if u need

**Comment by shawn-carrie** [comment]
Agreed, English would be great.

**Comment by sebastian-krempel** [comment]
The used vditor seems to already support English: https://github.com/Vanessa219/vditor/blob/master/README_en_US.md#static-methods
Please add a setting to vscode-office.

**Comment by aleon1220** [comment]
> The used vditor seems to already support English: https://github.com/Vanessa219/vditor/blob/master/README_en_US.md#static-methods Please add a setting to vscode-office.

It seems that the plugin vscode-office uses the Vditor markdown browser to display markdown files vditor https://b3log.org/vditor/

The Vditor author says that the settings to modify are:

`options.lang`

I dont know where to modify these settings in the vscode-office plugin

**Comment by aleon1220** [comment]
anyway i created a github issue in Vditor to request defaulting to English
https://github.com/Vanessa219/vditor/issues/1108

**Comment by pablomandolesi** [comment]
I have the same issue. I would not recommend changing the default language, as it would be going against the creator's choice, which I respect.
But I would rather facilitate a way to select another language.
Thanks!

**Comment by yyqwerty** [comment]
Hello! Are there any updates on support of other languages?

**Comment by fmarslan** [comment]
Hi! is there any plan for this issue?

**Comment by fmarslan** [comment]
I have a PR to this issue, if you accept it and release others may benefit.

**Comment by cweijan** [comment]
Toolbar has been modified to English in version 2.8.0.
