### ISSUE TITLE
vditor编辑器没有替换功能

### ISSUE THREAD

**Issue by jxjxjhjh** [cweijan/vscode-office#13]
ctrl+f可以查找，但是ctrl+h没有替换功能，是要等vditor更新吗？
能不能加一个快捷键切换md编辑器功能，我之前不知道是在哪个插件里见过，按快捷键弹出选项可以选择编辑器。

**Comment by cweijan** [comment]
右键MD文件, 在菜单选择以Text View就可以用默认编辑器打开, 自己替换, vditor现在没有提供这种功能.
![image](https://user-images.githubusercontent.com/27798227/101283195-e73cfd00-3813-11eb-9cea-59a6b7c641c3.png)
