### ISSUE TITLE
VSCode安装了Office Viewer(Markdown Editor)插件，但是打不开md文件

### ISSUE THREAD

**Issue by panyongkang** [cweijan/vscode-office#132]
昨天还好好的，今天重新打开一看就不行了，卸载重装也没用，请问什么情况？

**Comment by cweijan** [comment]
估计你点错修改了md的默认编辑器.

**Comment by panyongkang** [comment]
我的VSCode版本是1.64的，这个插件更新后不支持了吗？我改回2.7.2之前的倒是能用。要不要升级VSCode版本呢？

**Comment by cweijan** [comment]
你的不能用是指什么呢?
如果是打开了默认编辑器, 你试下这个菜单.
![image](https://user-images.githubusercontent.com/27798227/194536583-c481086d-94e2-4dc2-83ee-ddb6325585b9.png)

**Comment by panyongkang** [comment]
换成了2.7.3最新版本插件设置了默认编辑器就是打不开，内置的都可以打开，我暂时先改回2.7.2上个版本的才能正常打开md文件。不知道什么情况？










------------------&nbsp;Original message&nbsp;------------------
From: "Weijan Chen"; 
Sendtime: Friday, Oct 7, 2022 6:49 PM
To: "cweijan/vscode-office"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [cweijan/vscode-office] VSCode安装了Office Viewer(Markdown Editor)插件，但是打不开md文件 (Issue #132)





 
你的不能用是指什么呢?
 如果是打开了默认编辑器, 你试下这个菜单.

**Comment by KondeU** [comment]
遇到了类似的情况，升级插件后无法打开，截图红框内的条子一直在加载中，但是就是主界面无显示。回退到2.7.2能正常工作。（VSCode版本如截图内）

![image](https://user-images.githubusercontent.com/29046736/206720194-641c4fa8-efaa-4434-80b5-3481080e25a1.png)

**Comment by sparrowZG** [comment]
> hello, 最后解决了吗，同样遇到vs1.64版本，使用office viewer 2.9.5不能打开md文件
 正准备更新下vs,看是否可以解决

**Comment by novelyear** [comment]
遇到了相似的情况，打不开“README.md”但是重命名为"ReadMe.md"后又可以打开了
