### ISSUE TITLE
katex parse error:Multple \tag

### ISSUE THREAD

**Issue by feiyang21282** [cweijan/vscode-office#134]
内部的katex版本怎么查看呢？这个版本好像不够新，最新的katex已经能支持下面的代码：
\begin{align}
   a&=b+c  \tag{2} \\\\
   d+e&=f   \tag{3}
\end{align}
而这个插件会显示错误：katex parse error:Multple \tag

**Comment by cweijan** [comment]
你这个本来就不行吧, 我在katex官网无法解析.
![image](https://user-images.githubusercontent.com/27798227/196340485-940f92f3-3436-4087-b6bf-9e089e1e696d.png)

**Comment by feiyang21282** [comment]
你好，你的信件我已收到。

**Comment by feiyang21282** [comment]
tag{2} \这个斜杠要改为两个斜杠，你再试试？
我刚用github，不熟悉，不知道为什么输入两个斜杠只能显示一个？不过我输入四个斜杠终于显示两个斜杠了。

**Comment by cweijan** [comment]
这个可以. 你用下最新版, 我已经将katex更新为最新版本了.
