### ISSUE TITLE
建议反馈：当标题栏的宽度不够时，可以支持自动换行吗

### ISSUE THREAD

**Issue by ghost** [cweijan/vscode-office#135]
如图
![QQ截图20221023184637](https://user-images.githubusercontent.com/32454224/197387806-6896398c-0632-4b5e-bbd4-9b111a9bd35d.png)
当地方够的时候标题会显示完整，
![QQ截图20221023184604](https://user-images.githubusercontent.com/32454224/197387845-896da99a-de6e-4812-ae55-674c5cca4b99.png)
当地方不够的时候，希望标题栏可以自动换行。

**Comment by cweijan** [comment]
这个是工具栏, 发布2.7.9修复了.
