### ISSUE TITLE
希望可以通过命令或者状态栏操作切换编辑器

### ISSUE THREAD

**Issue by Yang-yibu** [cweijan/vscode-office#138]
希望使用命令或者在状态栏提供操作，在 vscode 源码编辑与vscode-office编辑之间切换
![image](https://user-images.githubusercontent.com/23130670/197984852-12fde919-8519-40df-bf93-f29bc440527d.png)

**Comment by cweijan** [comment]
这个按钮就是, 你文档都不看下.
![image](https://user-images.githubusercontent.com/27798227/198250508-6bfcd08b-8d31-4d4f-83b4-1548330e99b0.png)

**Comment by Yang-yibu** [comment]
不好意思啊，当时只看得英文文档。
但这种方式不能完全满足我的目的。
现在安装插件后，全局搜索只能定位到具体的文件，不能到指定位置，也不能搜索。所以，我需要默认使用默认编辑器。所以操作按钮能放到我截图位置的话是比较理想的
