### ISSUE TITLE
xlsx 预览无法显示 Z 之后的列

### ISSUE THREAD

**Issue by myeeye** [cweijan/vscode-office#139]
只能显示到 Z 为止，之后的列就无法显示了。

**Comment by cweijan** [comment]
能给个excel看看吗, 我之前有处理过这个问题哦

**Comment by myeeye** [comment]
[文档下载链接](https://files.cnblogs.com/files/blogs/732058/Z.zip)

[渲染图下载链接](https://files.cnblogs.com/files/blogs/732058/Graph.zip)

**Comment by cweijan** [comment]
我用这个可以正常显示啊, 你的扩展版本多少

**Comment by myeeye** [comment]
v2.5.3

**Comment by cweijan** [comment]
最新版是2.8.0了哦, 你的vscode是不是没更新

**Comment by myeeye** [comment]
唔，是的，抱歉打扰了。
