### ISSUE TITLE
markdown编辑器无法正常显示任务列表

### ISSUE THREAD

**Issue by heartacker** [cweijan/vscode-office#14]
```markdown
## 1.2. 操作流程
  - [x] 1. 扫描当前exe的所在的目录。找出`uvproj`的文件。
  - [x] 2. 获取`uvproj` 文件里面的生成文件信息。
  - [x] 3. 查找同名的`uvopt`文件。并尝试获取他的配置信息。
  - [x] 4. 获取flash配置信息。
      1. 如果配置信息不是AC5121 或者不存在分区信息。则**直接退出**。
      2. 如果是AC5121，则执行下一步骤。
```
## 1.2. 操作流程
  - [x] 1. 扫描当前exe的所在的目录。找出`uvproj`的文件。
  - [x] 2. 获取`uvproj` 文件里面的生成文件信息。
  - [x] 3. 查找同名的`uvopt`文件。并尝试获取他的配置信息。
  - [x] 4. 获取flash配置信息。
      1. 如果配置信息不是AC5121 或者不存在分区信息。则**直接退出**。
      2. 如果是AC5121，则执行下一步骤。

![image](https://user-images.githubusercontent.com/1876302/117610272-07dafb80-b194-11eb-9684-d8ce0386328b.png)

**Comment by cweijan** [comment]
这个是vditor的bug, vditor bug挺多的.

**Comment by cweijan** [comment]
推荐的方式是在把点号后面的空格去掉, 避免引擎去解析成列表.
```markdown
## 1.2. 操作流程
  - [x] 1.扫描当前exe的所在的目录。找出`uvproj`的文件。
  - [x] 2.获取`uvproj` 文件里面的生成文件信息。
  - [x] 3.查找同名的`uvopt`文件。并尝试获取他的配置信息。
  - [x] 4.获取flash配置信息。
      1. 如果配置信息不是AC5121 或者不存在分区信息。则**直接退出**。
      2. 如果是AC5121，则执行下一步骤。
```
