### ISSUE TITLE
Is there a wiki or manual for settings.json ?

### ISSUE THREAD

**Issue by mengxianbin** [cweijan/vscode-office#14]
How can I look up any available options for this extension?

**Comment by cweijan** [comment]
There are currently 3 options about markdown, but this plugin does not intend to provide too many options.
![image](https://user-images.githubusercontent.com/27798227/102749158-76aee800-439e-11eb-9f37-a2d1f8df6cc1.png)

**Comment by mengxianbin** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
