### ISSUE TITLE
无法导出为pdf

### ISSUE THREAD

**Issue by liqiwenx** [cweijan/vscode-office#140]
v2.8.1, 使用 `Export PDF` 时vscode 终端”输出"提示：      
![image](https://user-images.githubusercontent.com/52438879/198914882-19d9bfd1-1175-4be1-a18a-ee8088e6a7d0.png)
 “`TypeError: Cannot read properties of undefined (reading 'sizeInBytes')`      

导出为html是正常的。

vscode版本：    
版本: 1.72.2 (user setup)
提交: d045a5eda657f4d7b676dedbfa7aab8207f8a075
日期: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
沙盒化: No

win版本：     
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2022/‎6/‎9
操作系统内部版本	19044.2130
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by cweijan** [comment]
你能提供一个不能导出的md吗, 我这边导出正常.

**Comment by liqiwenx** [comment]
> 你能提供一个不能导出的md吗, 我这边导出正常.

那可能是因为在我的电脑上文件加密软件(公司电脑) 导致的。我刚重新试了一下，我发现在点击`Export PDF`时会生成一个`html`文件, pdf应该也是由这个html进一步转换得到对吗, 这个文件被磁盘自动加密了, 可能是这个原因导致的文件读取失败, 我后续会在自己的电脑上再试一次, 然后反馈给你.

**Comment by cweijan** [comment]
是的
