### ISSUE TITLE
[BUG]安装插件以后，没有显示编辑栏

### ISSUE THREAD

**Issue by fantast1211** [cweijan/vscode-office#141]
- OS:win10
- Extension Version:all
作者你好，我想问一下为什么我在vscode中安装了这个插件，打开md文件没有渲染呢？是我操作哪里遗漏了吗？
![QQ图片20221031110445](https://user-images.githubusercontent.com/68722290/198922577-3272ef50-c719-4c30-97e6-a6b31f77cb39.png)

**Comment by cweijan** [comment]
尝试修改这里
![image](https://user-images.githubusercontent.com/27798227/198922713-fadb0a35-9240-4a4c-b3ba-c3f39ea4c985.png)
![image](https://user-images.githubusercontent.com/27798227/198922723-68432a6d-a259-4c74-a6b8-4627079e0405.png)

**Comment by fantast1211** [comment]
> 尝试修改这里 ![image](https://user-images.githubusercontent.com/27798227/198922713-fadb0a35-9240-4a4c-b3ba-c3f39ea4c985.png) ![image](https://user-images.githubusercontent.com/27798227/198922723-68432a6d-a259-4c74-a6b8-4627079e0405.png)

十分感谢您的解答
