### ISSUE TITLE
巨佬，编辑xlsx文件后如何保存啊

### ISSUE THREAD

**Issue by tscuite** [cweijan/vscode-office#145]
带带弟弟

**Comment by cweijan** [comment]
ctrl+s

**Comment by cweijan** [comment]
注意保存后格式会丢失

**Comment by tscuite** [comment]
膜拜巨佬，巨佬有统计过添加插件后对内存资源占用的增加量吗

**Comment by tscuite** [comment]
萌新是Mac，cmd+s用习惯了，感谢巨佬https://github.com/cweijan/vscode-office/issues/145#issuecomment-1299454958

**Comment by cweijan** [comment]
确实哦, 我没用过mac, 后面支持下cmd+s.

**Comment by tscuite** [comment]
> 确实哦, 我没用过mac, 后面支持下cmd+s.
已经很好用了巨佬，不影响体验
