### ISSUE TITLE
插件有时不生效的问题

### ISSUE THREAD

**Issue by Je5s1e** [cweijan/vscode-office#146]
如果电脑上还没有打开vscode，然后直接选择用vscode打开一个md文件，那么大概率插件不会生效，vscode上显示的是md的源码。而如果已经打开了vscode，再打开一个md文件，那么插件基本上就生效了。我之前总是打开md文件但是插件不生效，我也是试了很多次才发现这个规律，希望作者能解决一下^_^

**Comment by cweijan** [comment]
按这个流程试下
https://github.com/cweijan/vscode-office/issues/141#issuecomment-1296477592

**Comment by Je5s1e** [comment]
好的，感谢
