### ISSUE TITLE
右上角有一空缺

### ISSUE THREAD

**Issue by xyeluo** [cweijan/vscode-office#148]
- OS: win11(21H2)
- Extension Version: 2.8.1
- vscode:1.68.1

打开markdown文件右上角有黑色空缺，vscode主题是默认深色
![image](https://user-images.githubusercontent.com/76687240/200106361-b63bd984-5f20-4863-9953-8b4ee2b0f7f5.png)

**Comment by cweijan** [comment]
已发布2.8.2修复.

**Comment by xyeluo** [comment]
更新到2.8.2并重启vscode后，这个问题似乎依然存在
![image](https://user-images.githubusercontent.com/76687240/200154348-5840bac6-2a5e-4b4f-b268-795a7d90f506.png)
我并不会插件开发，所以尝试使用开发者工具寻找问题
看到`vditor-toolbar`宽度并没有占满一行，我去掉它的宽度限制后右上角的空缺就消失了
![image](https://user-images.githubusercontent.com/76687240/200154748-ea8daf83-5f09-4c76-98dd-d326d423cebe.png)
![image](https://user-images.githubusercontent.com/76687240/200154813-a26bf547-dd24-4874-90f1-0cb2480b5b9d.png)

**Comment by cweijan** [comment]
你的是什么主题

**Comment by xyeluo** [comment]
默认深色
![image](https://user-images.githubusercontent.com/76687240/200154970-3f4dc7c3-ee0c-4ecf-ba16-febd24c4be1c.png)

**Comment by cweijan** [comment]
哦哦, 你禁用了自动跟随主题, 默认白色确实没测试.

**Comment by cweijan** [comment]
已发布2.8.3修复.
