### ISSUE TITLE
markdown图片相对路径兼容性

### ISSUE THREAD

**Issue by templklklk** [cweijan/vscode-office#149]
### 问题描述
用这个插件编辑github pages markdown文章，遇到相对路径图片不显示的问题。
文章和图片如下：
- _posts/hello.md 
- assets/img/2020-7-29-hello-world/hello.png

在hello.md 里面有图片地址 /assets/img/2020-7-29-hello-world/hello.png，
github pages 能正常显示图片，
这个插件得改成 ../assets/img/2020-7-29-hello-world/hello.png 才行，和github pages冲突。
vscode自带markdown编辑器两种都兼容，都能显示图片。

### 期望方案
能否像vscode自带markdown编辑器那样两种都兼容？
或者能像typora一样提供typora-root-url选项，自行配置图片根目录，https://support.typora.io/Images/#relative-path-to-certain-folder

**Comment by cweijan** [comment]
这个功能太小众, 不计划支持. github page只是个静态服务器, 图片请求路径取决你的前端工程文件.

**Comment by LiuLarry** [comment]
> 这个功能太小众, 不计划支持. github page只是个静态服务器, 图片请求路径取决你的前端工程文件.

不一定小众啊，有的用vscode之前写的markdown文件，这样图片显示就不正常了

**Comment by LiuLarry** [comment]
> ### 问题描述
> 用这个插件编辑github pages markdown文章，遇到相对路径图片不显示的问题。 文章和图片如下：
> 
> * _posts/hello.md
> * assets/img/2020-7-29-hello-world/hello.png
> 
> 在hello.md 里面有图片地址 /assets/img/2020-7-29-hello-world/hello.png， github pages 能正常显示图片， 这个插件得改成 ../assets/img/2020-7-29-hello-world/hello.png 才行，和github pages冲突。 vscode自带markdown编辑器两种都兼容，都能显示图片。
> 
> ### 期望方案
> 能否像vscode自带markdown编辑器那样两种都兼容？ 或者能像typora一样提供typora-root-url选项，自行配置图片根目录，https://support.typora.io/Images/#relative-path-to-certain-folder

我也遇到这个问题了，这个问题你后面怎么解决的？

**Comment by templklklk** [comment]
> > ### 问题描述
> > 用这个插件编辑github pages markdown文章，遇到相对路径图片不显示的问题。 文章和图片如下：
> > 
> > * _posts/hello.md
> > * assets/img/2020-7-29-hello-world/hello.png
> > 
> > 在hello.md 里面有图片地址 /assets/img/2020-7-29-hello-world/hello.png， github pages 能正常显示图片， 这个插件得改成 ../assets/img/2020-7-29-hello-world/hello.png 才行，和github pages冲突。 vscode自带markdown编辑器两种都兼容，都能显示图片。
> > ### 期望方案
> > 能否像vscode自带markdown编辑器那样两种都兼容？ 或者能像typora一样提供typora-root-url选项，自行配置图片根目录，https://support.typora.io/Images/#relative-path-to-certain-folder
> 
> 我也遇到这个问题了，这个问题你后面怎么解决的？

为了兼容github pages，我后来不用这个插件，只能用typora了

**Comment by LiuLarry** [comment]
> 

typora收费啊, 我改了下代码,hard code了下, 勉强能用了

**Comment by LiuLarry** [comment]
> > > ### 问题描述
> > > 用这个插件编辑github pages markdown文章，遇到相对路径图片不显示的问题。 文章和图片如下：
> > > 
> > > * _posts/hello.md
> > > * assets/img/2020-7-29-hello-world/hello.png
> > > 
> > > 在hello.md 里面有图片地址 /assets/img/2020-7-29-hello-world/hello.png， github pages 能正常显示图片， 这个插件得改成 ../assets/img/2020-7-29-hello-world/hello.png 才行，和github pages冲突。 vscode自带markdown编辑器两种都兼容，都能显示图片。
> > > ### 期望方案
> > > 能否像vscode自带markdown编辑器那样两种都兼容？ 或者能像typora一样提供typora-root-url选项，自行配置图片根目录，https://support.typora.io/Images/#relative-path-to-certain-folder
> > 
> > 
> > 我也遇到这个问题了，这个问题你后面怎么解决的？
> 
> 为了兼容github pages，我后来不用这个插件，只能用typora了


typora收费啊, 我改了下代码,hard code了下, 凑合用了

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4577940/209306830-06c878f7-ca75-440b-a53c-a0333ef8db4e.png">

**Comment by cweijan** [comment]
发布了2.9.5版本, 支持了${workspaceDir}变量, 以及支持以工作空间为图片基础目录,  示例:
```json
{
    "vscode-office.pasterImgPath": "${workspaceDir}/image/${fileName}/${now}.png",
    "vscode-office.workspacePathAsImageBasePath": true
}
```
