### ISSUE TITLE
class file not processed correctly.

### ISSUE THREAD

**Issue by liudonghua123** [cweijan/vscode-office#15]
I have an issue with java project when I try to ctrl-click (execute go to definition) some symbols in Java. And finally, @maoziliang found the key problems. see more details on https://github.com/redhat-developer/vscode-java/issues/1741#issuecomment-746128965.

**Comment by liudonghua123** [comment]
I tried to check the code, and found that maybe the following code have some problems.

https://github.com/cweijan/vscode-office/blob/503e7edca85ec4c99f0413ed24e899aa3d278ed4/src/provider/officeViewerProvider.ts#L114-L134

**Comment by liudonghua123** [comment]
I debugged the code and found the cause, the `uri.fsPath` is not expected as a real path of the file system.

![image](https://user-images.githubusercontent.com/2276718/102450587-b9588380-4071-11eb-9b7a-032a99b9aedc.png)

Another problem with the error output is the wrong channel name of the output.

![image](https://user-images.githubusercontent.com/2276718/102450687-f7ee3e00-4071-11eb-830b-52114cd96275.png)

In my opinion, maybe it's too complicated to handle class only using `fernflower` decompiler, I advice to remove this feature in this extension. Leave the job to `vscode-java` extension.

**Comment by cweijan** [comment]
Class viewer is java decompiler, This is a bug that cannot decompile the classes in the jar. I will fix it later. I am a little busy at the moment.

**Comment by liudonghua123** [comment]
@cweijan However, If I execute go to definition (or ctrl+click some classes of Java), the `vscode-java` can open the corresponding source code if available and jump to the right position. If rewrite the `.class` file handler, the source code will never open.

**Comment by cweijan** [comment]
> @cweijan However, If I execute go to definition (or ctrl+click some classes of Java), the `vscode-java` can open the corresponding source code if available and jump to the right position. If rewrite the `.class` file handler, the source code will never open.

Thanks feedback.
