### ISSUE TITLE
copy local picture to ssh-remote md file

### ISSUE THREAD

**Issue by HEUBITLYJ** [cweijan/vscode-office#154]
hello，i want to copy image to a ssh-remote md file， the extension show:

 There is not an image in the clipboard.

**Comment by cweijan** [comment]
You can't paste pictures directly, they don't share the clipboard, but you can upload pictures via this button in the toolbar.
![image](https://user-images.githubusercontent.com/27798227/201579803-8e1b4fa2-0c1d-4397-9e1f-7084ac98dc19.png)
