### ISSUE TITLE
建议增加源码模式快捷键

### ISSUE THREAD

**Issue by sheldon123z** [cweijan/vscode-office#156]
如果可以增加一个源码模式快捷键就很方便了，一般编辑markdown写公式之类的很需要看源码，因为katex有时候会不兼容一些公式指令，但是在网页端发布则大部分使用mathjax，增加快捷键源码模式可以很方便编辑

**Comment by cweijan** [comment]
点击这个就可以显示源markdown, 编辑器不能跟踪markdown的位置, 增加快捷键没有意义, 只能跳转到markdown开头.
![image](https://user-images.githubusercontent.com/27798227/203518712-051fcef3-eba3-4b67-baba-9a317c78b4fc.png)
