### ISSUE TITLE
增加 markdown 大纲栏宽度的设置

### ISSUE THREAD

**Issue by huangcb01** [cweijan/vscode-office#159]
当我使用左右分屏时，markdown 编辑器的大纲栏占了太多空间，我发现修改用户目录下的 `.vscode\extensions\cweijan.vscode-office-2.9.0\resource\vditor\vditor.css` 中的 `.vditor-outline` 可以改变大纲栏宽度，所以能否在拓展设置中提供一个接口供用户更加方便地修改大纲栏宽度。如果能够在编辑器中用鼠标拖动调整大纲栏宽度，并且加上开关大纲栏的按钮就更好了。

![image](https://user-images.githubusercontent.com/78298502/202733213-2638ba59-1a97-4aa7-a889-8e6621a93084.png)

**Comment by cweijan** [comment]
发布了2.9.1版本, 现在在小屏会将大纲宽度减少为150px.
另外点这个按钮就可以关闭大纲的.
![image](https://user-images.githubusercontent.com/27798227/203518997-d240f0f6-3496-4999-b957-6a54d3b7a236.png)
