### ISSUE TITLE
希望 Markdown 支持 Remote SSH 模式下的图片粘贴

### ISSUE THREAD

**Issue by Lin-Guanguo** [cweijan/vscode-office#160]
现在 Remote SSH 图片粘贴会读取远程机器上的剪切版, 希望增加配置选项, 选择读取 "远程剪切板" 或 "本地剪切板"

另一个 Markdown 的图片粘贴插件 Paste Image 也是默认读取 "远程剪切板", 在这个 Issue 里有人提出了解决方法, 并开发出了读取 "本地剪切板" 的版本 Paste Image from local pc
https://github.com/mushanshitiancai/vscode-paste-image/issues/44
https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-clipboard

可惜的是这个插件不能和 vscode-office 一起工作. 希望 vscode-office 也能支持读取 "本地剪切板"

**Comment by cweijan** [comment]
你给的链接里并没有粘贴远程图片的解决方案.
在远程中你可以通过上传图片按钮来选择图片.
![image](https://user-images.githubusercontent.com/27798227/203504947-e3fc2085-fbc8-4c51-b37b-1441e8959f3d.png)

**Comment by aoliong** [comment]
office markdown是我使用过最好用的markdown插件，非常感谢作者的贡献。

写作过程中经常会插入图片，所以如果可以直接使用“ctrl+v”或者其它快捷键来插入图片，就会大大的提升写作的体验。

因为本人喜欢在linux下写代码，所以会使用WSL+vscode这样的搭配。这时直接在linux上写作，也是最直接的。但当前还不能直接使用“ctrl+v”来粘贴图片，非常可惜。

本人发现一个临时的办法：

1. 安装“Markdonw Paste”插件
2. 使用“shift+win+s”截屏
3. 再选择“Edit In VSCode”按钮，进入vscode的编辑模式
4. 再使用“ctrl+alt+v”来粘贴图片。

这样可以达到一个类似的效果。当然，这里多了一个“Edit In VSCode”的操作，并不是最好的体验。还是希望作者可以考虑“远程粘贴板”的方案。

十分感谢

> 现在 Remote SSH 图片粘贴会读取远程机器上的剪切版, 希望增加配置选项, 选择读取 "远程剪切板" 或 "本地剪切板"
> 
> 另一个 Markdown 的图片粘贴插件 Paste Image 也是默认读取 "远程剪切板", 在这个 Issue 里有人提出了解决方法, 并开发出了读取 "本地剪切板" 的版本 Paste Image from local pc [mushanshitiancai/vscode-paste-image#44](https://github.com/mushanshitiancai/vscode-paste-image/issues/44) https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-clipboard
> 
> 可惜的是这个插件不能和 vscode-office 一起工作. 希望 vscode-office 也能支持读取 "本地剪切板"
