### ISSUE TITLE
why did you hide table tools ?

### ISSUE THREAD

**Issue by fmarslan** [cweijan/vscode-office#162]
https://github.com/cweijan/vscode-office/blob/c35c2577d5c2d67749f4024db73511dcf3729a49/resource/vditor/index.css#L14

I think these tools are very useful. if there is an important reason, we could make it connect to a parameter, or else could open directly.

![image](https://user-images.githubusercontent.com/12278069/203837454-92327a29-7200-4f13-9ae8-af779fb089c4.png)

**Comment by cweijan** [comment]
Thanks for your feedback, here is to hide all the floating toolbars, because they affect the editing experience, I will try to restore the table toolbar.

**Comment by cweijan** [comment]
Fix at version 2.9.2.

**Comment by fmarslan** [comment]
thanks for your quick reaction.
But, it is better if we could make it a configuration.  I don't know how can make it. If I find a way for this, I will send a PR.

Because it is well for me but this feature can be a problem for some screens as you said.
