### ISSUE TITLE
大纲导出调整

### ISSUE THREAD

**Issue by Grey-Wind** [cweijan/vscode-office#165]
在导出至PDF与DOCX时移除大纲
导出为HTML时自动将大纲移至左侧并生成书签(目录)代码(html与css)可参考[这个csdn](https://blog.csdn.net/qq_34581334/article/details/79812505)

**Comment by cweijan** [comment]
发布了版本2.9.2, 目录是用来生成大纲的, 现在导出html和docx将不再生成目录, pdf还是保留.
