### ISSUE TITLE
csv中文乱码

### ISSUE THREAD

**Issue by jiawuhia123** [cweijan/vscode-office#17]
![image](https://user-images.githubusercontent.com/74997626/102859833-af66c400-4467-11eb-8cf9-d1cdbedf8491.png)
![image](https://user-images.githubusercontent.com/74997626/102859862-ba215900-4467-11eb-9f48-040547999775.png)

vscode上使用的版本：1.8.10

**Comment by cweijan** [comment]
因为excel默认保存的csv格式是gbk, 现在只能支持utf8格式.

**Comment by jiawuhia123** [comment]
> 因为excel默认保存的csv格式是gbk, 现在只能支持utf8格式.

后续版本会对gbk格式支持吗？

**Comment by cweijan** [comment]
目前不打算支持, 建议自行调整编码为UTF8.
