### ISSUE TITLE
[BUG]在vscode保存xlsx会导致所有格式被清除

### ISSUE THREAD

**Issue by kaxifakl** [cweijan/vscode-office#171]
- OS:
- Extension Version:

在vscode中保存有格式的表格文件会导致
下拉列表、格式、样式全部消失

**Comment by cweijan** [comment]
主要是实现预览功能, 保存是附加的小功能, 无法实现一个excel编辑器.

**Comment by kaxifakl** [comment]
可以加个开关把保存功能关掉吗，这个功能没有比有好

**Comment by cweijan** [comment]
只有你按ctrl+s才会保存.. 不会自动保存.

**Comment by kaxifakl** [comment]
很容易误操作

**Comment by cweijan** [comment]
发布了2.9.2版本, 现在保存xlsx时会弹出一个确认框.

**Comment by kaxifakl** [comment]
感觉加配置开关好一点，默认开启保存，弹窗会影响其他正常需要保存的用户，而且vscode的弹窗的体验不是很好
