### ISSUE TITLE
[BUG] 有的pdf文件打开乱码

### ISSUE THREAD

**Issue by 695959653** [cweijan/vscode-office#172]
- OS: windows11
- Extension Version: 2.9.2
pdf文件是没问题的, 一些pdf文件打开就乱码,一些不会
![image](https://user-images.githubusercontent.com/34927091/206404059-c72164c2-37b1-40fe-8a4b-a2396d41ac1a.png)

**Comment by cweijan** [comment]
这是这个pdf本身就乱码吧

**Comment by 695959653** [comment]
这个pdf文件是没问题的, 下面这个是用wps打开的情况
![image](https://user-images.githubusercontent.com/34927091/206405896-32129750-384e-4097-a3f5-813a72fcd2fb.png)

**Comment by 695959653** [comment]
我将文件上传上来, 你帮忙看看什么原因, 我换了一台电脑也是有这个情况.
[《TCP-IP详解.卷1-协议》.pdf](https://github.com/cweijan/vscode-office/files/10183880/TCP-IP.1-.pdf)

**Comment by cweijan** [comment]
看起来是因为这个pdf中的字体不支持, 你试下在下面这个地址打开看正不正常, 如果正常我可以通过升级pdf.js版本来解决.
https://mozilla.github.io/pdf.js/web/viewer.html
![image](https://user-images.githubusercontent.com/27798227/206407446-51bc318c-c8c8-4827-b4ca-b24b2abaedab.png)

**Comment by 695959653** [comment]
> 看起来是因为这个pdf中的字体不支持， 你试下在下面这个地址打开看正不正常， 如果正常我可以通过升级pdf.js版本来解决. https://mozilla.github.io/pdf.js/web/viewer.html ![图像](https://user-images.githubusercontent.com/27798227/206407446-51bc318c-c8c8-4827-b4ca-b24b2abaedab.png)

这个链接可以正常打开这个文件

**Comment by cweijan** [comment]
已在2.9.3修复, 需要联网.

**Comment by iHappinessLife** [comment]
> 已在2.9.3修复, 需要联网.

Not chromium found, export fail.
怎么解决？只装了最新版本的Edge，Mac OS系统。
