### ISSUE TITLE
Markdown有没有更改默认的换行方法的设置项？

### ISSUE THREAD

**Issue by szw0407** [cweijan/vscode-office#174]
默认应该是空一行显示为换行，源代码的换行是直接跟在后面的。
目前发现在GitHub里面渲染Markdown的行内公式必须单独一行，不然会直接保留源码。
希望这里可以给一个选项，在设置里面启用，让换行严格按照“空一行”的要求。
当然可能已经能设置了，但是我没看见。
（看到都是中文issue就放心了）

**Comment by cweijan** [comment]
... 行内公式你还换行干嘛, 多行要用代码块.
```js
1+1=2
2+2=4
```

**Comment by szw0407** [comment]
`something$\alpha^2$`
```
something
$\alpha^2$
```
这两个东西，按理说应该是一样的，但是在github上面预览README.MD似乎只认识第二个。
我只是希望能允许用户选择按第二个写法，而不是非得把第二个写法渲染成如下面的结果
```
something

$\alpha^2$
```

**Comment by szw0407** [comment]
GitHub里面确实不认识$\alpha$，保留了原文本

**Comment by cweijan** [comment]
那是因为你把数学公式给包含在`里面, 不支持识别, markdown的规范就是这样, 我看vditor的渲染是正常的.
