### ISSUE TITLE
[BUG] markdown 文件无法导出 pdf 文件 

### ISSUE THREAD

**Issue by Jeromestein** [cweijan/vscode-office#176]
- OS: Windows 10 21H1 (19043.1889)
- Extension Version: v2.9.3
- VS Code Version: 1.74.1

今天无法直接生成pdf文件了，但会生成一个html文件。
回头试了一下，之前能成功生成的md文件现在也不行了。
怀疑与插件更新有关。

output报错:
```
TypeError: Cannot read properties of undefined (reading 'sizeInBytes')
```

**Comment by cweijan** [comment]
你是最近有更新系统吧, pdf导出逻辑没变的.

**Comment by Jeromestein** [comment]
> 你是最近有更新系统吧, pdf导出逻辑没变的.

没更新操作系统，只是把vscode升级了。 我windows和mac上的导出都失败了，原来是可以的。 你的windows导出没问题吗？

**Comment by cweijan** [comment]
已发布2.9.5版本修复.
