### ISSUE TITLE
自定义粘贴图片路径希望能基于当前工作区根目录

### ISSUE THREAD

**Issue by orion-tan** [cweijan/vscode-office#179]
默认是基于当前文章目录，希望能基于工作区根目录，比如添加一个 ${workspaceDir}变量
![image](https://user-images.githubusercontent.com/60279276/210490749-b9f6dc9b-093f-4e3c-a09a-1950dac00178.png)

**Comment by maxiaogood** [comment]
强烈建议

**Comment by maxiaogood** [comment]
/**
     * 获取当前所在工程根目录，有3种使用方法：<br>
     * getProjectPath(uri) uri 表示工程内某个文件的路径<br>
     * getProjectPath(document) document 表示当前被打开的文件document对象<br>
     * getProjectPath() 会自动从 activeTextEditor 拿document对象，如果没有拿到则报错
     * @param {*} document 
     */
    getProjectPath(document) {
        if (!document) {
            document = vscode.window.activeTextEditor ? vscode.window.activeTextEditor.document : null;
        }
        if (!document) {
            this.showError('当前激活的编辑器不是文件或者没有文件被打开！');
            return '';
        }
        const currentFile = (document.uri ? document.uri : document).fsPath;
        let projectPath = null;
        let workspaceFolders = vscode.workspace.workspaceFolders.map(item => item.uri.path);
        // 由于存在Multi-root工作区，暂时没有特别好的判断方法，先这样粗暴判断
        // 如果发现只有一个根文件夹，读取其子文件夹作为 workspaceFolders
        if (workspaceFolders.length == 1 && workspaceFolders[0] === vscode.workspace.rootPath) {
            const rootPath = workspaceFolders[0];
            var files = fs.readdirSync(rootPath);
            workspaceFolders = files.filter(name => !/^\./g.test(name)).map(name => path.resolve(rootPath, name));
            // vscode.workspace.rootPath会不准确，且已过时
            // return vscode.workspace.rootPath + '/' + this._getProjectName(vscode, document);
        }
        workspaceFolders.forEach(folder => {
            if (currentFile.indexOf(folder) === 0) {
                projectPath = folder;
            }
        })
        if (!projectPath) {
            this.showError('获取工程根路径异常！');
            return '';
        }
        return projectPath;
    },

**Comment by cweijan** [comment]
发布了2.9.5版本, 支持了${workspaceDir}变量, 以及支持已工作空间为图片基础目录,  示例:
```json
{
    "vscode-office.pasterImgPath": "${workspaceDir}/image/${fileName}/${now}.png",
    "vscode-office.workspacePathAsImageBasePath": true
}
```
