### ISSUE TITLE
Built-in themes conflicting with existing ones (One Dark & Material Icon)

### ISSUE THREAD

**Issue by QuentiumYT** [cweijan/vscode-office#18]
When starting VSC with Material Icon Theme as enabled real extension, it conflicts with the one included in yours.
Custom icons doesn't work and a few other configs...
Is it possible to disable built in themes and icons? Or at least locally

Have to remove that every update
```
"themes": [
	{
		"label": "One Dark Modern",
		"uiTheme": "vs-dark",
		"path": "./theme/OneDark-Modern.json"
	}
],
"iconThemes": [
	{
		"id": "material-icon-theme",
		"label": "Material Icon Theme",
		"path": "./dist/material-icons.json",
		"_watch": true
	}
],```

**Comment by cweijan** [comment]
You can change theme manual.
![image](https://user-images.githubusercontent.com/27798227/120055123-9d1c3200-c066-11eb-94cd-58f43a0bb8a9.png)
![image](https://user-images.githubusercontent.com/27798227/120055128-a1484f80-c066-11eb-8c5a-2ce3b8566e11.png)

**Comment by cweijan** [comment]
I think you think the name conflicts, I will change his name in the next version.

**Comment by QuentiumYT** [comment]
I know i can change it, but looks like it still conflicts, you can try that, i will tell you

**Comment by QuentiumYT** [comment]
The update LGTM, no more conflicts, thanks!
