### ISSUE TITLE
能否调整代码块适应浅色主题背景

### ISSUE THREAD

**Issue by huangqiangxiong** [cweijan/vscode-office#180]
你好，这个软件感觉使用起来还不错，只是有个小问题：

浅色主题背景下代码块看起来颜色偏灰，不明显：
![light](https://user-images.githubusercontent.com/30267326/210589024-9a2b4f84-fcef-4343-b934-0ce9aec7f750.jpg)

深色主题背景下代码块看起来还可以：
![dark](https://user-images.githubusercontent.com/30267326/210589005-fa47f0fd-54b4-4138-8e90-be6e9cb66198.jpg)

能否在浅色主题背景下能显示的像vscode markdown preview插件一样显著的高亮颜色显示代码块：
![preview](https://user-images.githubusercontent.com/30267326/210588943-617af62f-128a-4601-a71c-529ca0ae1911.jpg)

或者有比较简单的方法配置一下自行修改代码块的高亮显示效果？

>注：我用的是2.9.4版本。

**Comment by huangqiangxiong** [comment]
发现代码块主体预览可以选择代码块显示高亮方案，但是每次打开都要重新选，在settings.json里能固定配置吗？

**Comment by cweijan** [comment]
已发布至2.9.5版本.
