### ISSUE TITLE
[BUG] Dark Mode doesn't work with excel, pdf

### ISSUE THREAD

**Issue by vanbang9710** [cweijan/vscode-office#184]
- OS: Windows 10 Version 21H2 (Build 19044.2486)
- Extension Version: 2.9.5 2023-1-12
Dark Mode still works with .docx, but not .xlsx and .pdf
![image](https://user-images.githubusercontent.com/52906188/215321207-6a4b0cf1-b0ec-4254-8dbe-abab93bf3ac8.png)
![image](https://user-images.githubusercontent.com/52906188/215321100-91515fd0-4397-4362-859b-81c152925fd5.png)
![image](https://user-images.githubusercontent.com/52906188/215321180-766806e3-2a94-4b28-80c6-8fdc2a920850.png)

**Comment by cweijan** [comment]
They do not support dark mode.
