### ISSUE TITLE
怎样设置背景颜色以及图片保存路径?

### ISSUE THREAD

**Issue by cym2050** [cweijan/vscode-office#19]

**Comment by cweijan** [comment]
颜色可以勾选这个选项, 图片保存路径不支持.
![image](https://user-images.githubusercontent.com/27798227/120576578-9a9a4d80-c455-11eb-9d85-35c69e242a99.png)

**Comment by cym2050** [comment]
> 颜色可以勾选这个选项, 图片保存路径不支持.
> ![image](https://user-images.githubusercontent.com/27798227/120576578-9a9a4d80-c455-11eb-9d85-35c69e242a99.png)

谢谢

**Comment by colladovictor** [comment]
@cweijan the owner of this issue agreed with the fix. Therefore we should close this issue.

**Comment by cweijan** [comment]
最新版支持配置图片路径了
![image](https://user-images.githubusercontent.com/27798227/172294894-c39e0470-0684-4b52-ad4e-c87adbc400af.png)
