### ISSUE TITLE
Swapped Delete Column/Row Hover-Text in Markdown Table Editor

### ISSUE THREAD

**Issue by JHUDMC** [cweijan/vscode-office#191]
Type: <b>Bug</b>

1. Open a .md file.
2. Create a table if one does not exist already.
3. Hover over the delete column or delete row button.
4. Observe the correct icon but the incorrect hover-text.

Extension version: 2.9.5
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by cweijan** [comment]
Fixed in version 2.9.6.
