### ISSUE TITLE
[BUG] XXX.md 文件名大小写变更后再次尝试打开 xxx.md 文件报错

### ISSUE THREAD

**Issue by PaiGack** [cweijan/vscode-office#193]
- OS: Window10
- Extension Version: 
```md
office viewer v2.9.5

Published 3/5/2021, 15:04:43
Last released 1/12/2023, 18:32:49
Last updated 2/6/2023, 16:49:15
Identifier cweijan.vscode-office
```
## 操作步骤
- 使用 vscode 打开一个空文件夹
- 新建一个 a.md 文件
- 使用 vscode 打开该文件
- 将 a.md 文件名更改为 A.md
- vscode 报错
- 关闭 tab 后重新打开，继续提示报错

## 报错信息
Visual Studio Code 弹窗信息
![image](https://user-images.githubusercontent.com/42209827/219255028-ea16dba6-9ec8-49a9-ad43-1ad7b80b4f35.png)

md 文件渲染 tab 信息
![image](https://user-images.githubusercontent.com/42209827/219255109-a16d9191-22ab-494f-b827-8942af9fbeb7.png)

**Comment by cweijan** [comment]
这个是VSCode的bug, 扩展无法解决
