### ISSUE TITLE
[BUG] Pagination navigator blocking document view

### ISSUE THREAD

**Issue by damiansb** [cweijan/vscode-office#197]
- OS: Windows 11
- Extension Version: 2.9.5

When a document has too many pages, the page navigator is stuck above the view area. It would be nice if there was an option to turn it off, or just display it in a different way, like a drop down or something of the kind.

See the image below for an example of the issue.

![WhatsApp Image 2023-02-22 at 00 59 23](https://user-images.githubusercontent.com/468669/220518519-f14b4aa9-a7be-4733-bc29-140d53713816.jpeg)

**Comment by cweijan** [comment]
Fixed in version 2.9.6.
