### ISSUE TITLE
工具栏能隐藏吗？

### ISSUE THREAD

**Issue by soulofshadow** [cweijan/vscode-office#198]
![WeChatb5e7b1a4163f3d841cd657f3aa20cd4d Medium](https://user-images.githubusercontent.com/95683271/220712331-90cc566a-daa5-4dec-80ab-0bc8c6365804.jpeg)

能把这个缩起来吗？

**Comment by cweijan** [comment]
已发布2.9.6版本支持.
![image](https://user-images.githubusercontent.com/27798227/223366093-e0d547eb-5d06-4210-a9a0-9a6d3bb24480.png)
