### ISSUE TITLE
Outdated Version von vscode-restclient

### ISSUE THREAD

**Issue by AnWeber** [cweijan/vscode-office#2]
Why is an outdated version of [vscode-restclient](https://github.com/Huachao/vscode-restclient) is used instead referencing the current version. You could simply reference the depenency in the [extension manifest](https://code.visualstudio.com/api/references/extension-manifest) with key extensionDependencies

**Comment by cweijan** [comment]
There is a bug in vscode-restclien, and the integration has been enhanced.
