### ISSUE TITLE
大纲栏能否隐藏

### ISSUE THREAD

**Issue by LstHeart** [cweijan/vscode-office#20]
很感谢作者开发这款插件，不过在 VSCode 写 markdown 时，左侧的大纲栏总是显示，感觉有点占空间，请问大纲栏能否通过配置项进行关闭呢？或者类似于 typora 一样有按钮可以切换隐藏？

![image](https://user-images.githubusercontent.com/18585439/120913004-6c6f7480-c6c6-11eb-9c8e-bdc48aa54417.png)

**Comment by shaonianruntu** [comment]
非常需要这一功能，特别是在split editor 的时候，横向的宽度本来就没多少，特别是在笔记本上。此时，再显示一个大纲视图，markdown的主题文本基本看不到了。
希望可以支持大纲根据当前页面的宽度自动选择是否隐藏，并且也支持快捷键或者按钮的关联，可以设置是否隐藏大纲。或者添加插件的vscode设置，让用户手动选择是否永久隐藏或者显示。

**Comment by lmovse** [comment]
希望可以有配置项.

**Comment by cweijan** [comment]
新版可以了.
