### ISSUE TITLE
Git对比版本时，能够显示md原文，方便直观的比对变更内容。

### ISSUE THREAD

**Issue by lee-cq** [cweijan/vscode-office#200]
目前在GIT界面查看文件变更
![image](https://user-images.githubusercontent.com/47050568/221414305-f768969a-dea5-4c43-b275-e0c27b72bd51.png)
即便点击了 Edit in VSCode 也不能像原来那样的直观的文件变动。
![image](https://user-images.githubusercontent.com/47050568/221415181-8dbafe8a-eea0-4291-906a-2ec2700f19e5.png)
希望在GIT标签下可以直接显示原文，而不是渲染后的内容。

**Comment by Ainevsia** [comment]
是的，我也是diff的时候不太知道应该怎么取消渲染

**Comment by cweijan** [comment]
已在版本3.2.0支持.
