### ISSUE TITLE
Scroll sync on WYSIWYG markdown view 

### ISSUE THREAD

**Issue by thiagofigcosta** [cweijan/vscode-office#203]
Can we sync the scroll between the the markdown source code view (when opened) and the WYSIWYG markdown view ?
By scrolling down one of them the other could follow the scroll!

Also, when searching something on the vscode search panel, when the user click the matching line the WYSIWYG markdown view opens on the wrong positon (if the matching line is not on beginning).
![image](https://user-images.githubusercontent.com/10348513/221878466-f3eea26c-1e0c-47f9-b394-86e4b4f3b2cb.png)

**Comment by elerson** [comment]
+1

**Comment by ceconelli** [comment]
up

**Comment by janiodev** [comment]
+1

**Comment by cweijan** [comment]
VSCode did not provide the required data, this function cannot be implemented.

**Comment by thiagofigcosta** [comment]
I'm not sure if this helps, but there is an extension that can sync two panes on vscode (dqisme.sync-scroll) https://github.com/dqisme/vscode-sync-scroll it works fine for two open files on vscode, I tested several times. However it doesn't work with office-viewer's WYSIWYG markdown view. But it might help on this feature!

Thank you for the replies and for this great extension!
