### ISSUE TITLE
希望能通过打开md后缀文件来启用插件。

### ISSUE THREAD

**Issue by yijiangchengming** [cweijan/vscode-office#207]
在文件管理器双击打开md文件并不会渲染，需要在vscode再打开一次。
现在希望直接双机文件打开vscode如何就开始渲染。

**Comment by rfhits** [comment]
vscode 自己有设置 *.md 的打开方式呀
![image](https://user-images.githubusercontent.com/70683664/224482544-a180a17f-bcf3-495a-947b-ed2313e00533.png)

**Comment by rfhits** [comment]
对了，右键打开的 md 文件就能调出这个菜单，实在不行搜索一下如何为 vscode 设置文件的默认打开方式。

**Comment by yijiangchengming** [comment]
> 对了，右键打开的 md 文件就能调出这个菜单，实在不行搜索一下如何为 vscode 设置文件的默认打开方式。

我设置了打开方式，但它并不生效。
![image](https://user-images.githubusercontent.com/30022966/224484007-5c47356b-33d7-491b-be7f-cdb2c8af9759.png)
重新测试了一下，只有第二次开始才渲染。
关闭vscode，双击md文件，vscode被首次打开，此时不渲染。
再资源管理器双击任意md文件，vscode打开新的选项卡，此时渲染。

**Comment by rfhits** [comment]
要不重启一下电脑或者 vscode，这个东西可能得开发者复现出来才能修。。。

**Comment by cweijan** [comment]
这个去查一下vscode的设置, 我没遇过这种情况, 可以先试下清空vscode的设置.
