### ISSUE TITLE
[BUG] Excel formulas parsing

### ISSUE THREAD

**Issue by MrFuxus** [cweijan/vscode-office#229]
- OS: MacOS
- Extension Version: v3.1.2

We would like to use the extension to allow editing some inputs for excel spreadsheets. Although after saving the file we notice that all formulas are replaced by hardcoded values. Can a setting be introduced not to overwrite formulas as edited input should be reflected on other cells?

**Comment by cweijan** [comment]
The component can only provide table rendering.
