### ISSUE TITLE
[BUG] zip文件内容乱码

### ISSUE THREAD

**Issue by Ovalene2333** [cweijan/vscode-office#240]
- OS:WIndows 11 
- Extension Version:3.1.5 2023-5-18
- 在打开含有中文路径和文件名的zip压缩文档的时候会出现解码错误出现乱码的情况
![}`3~83ZLD0D1D54FU~YGJOK](https://github.com/cweijan/vscode-office/assets/112636711/4f6dfa99-af19-46e2-bcf0-f4467d228859)
并且会出现压缩文档支持功能的内部没有适配主题的问题

**Comment by cweijan** [comment]
已在版本3.3.0支持切换gbk编码.

<img width="1003" alt="image" src="https://github.com/cweijan/vscode-office/assets/27798227/aa566ad8-a4a4-45ff-9864-772b2d8f47a0">
