### ISSUE TITLE
中文标点取消自动补全

### ISSUE THREAD

**Issue by alephpi** [cweijan/vscode-office#243]
首先感谢你的项目！

在使用中我注意到中文引号、括号输入左半部分，会自动补全为英文的右半部分，需要手动删除，有点烦人。能否取消之？

**Comment by yin0713** [comment]
这个可以有个选项的

**Comment by alephpi** [comment]
> 这个可以有个选项的

哦是嘛，我找找

**Comment by hidezember** [comment]
请问这个选项在哪里呀，设置中实在没有找到……

**Comment by alephpi** [comment]
> 请问这个选项在哪里呀，设置中实在没有找到……

我也没有找到，可能楼上说的是这个可以有（但还没有）😂

**Comment by hidezember** [comment]
> > 请问这个选项在哪里呀，设置中实在没有找到……
> 
> 我也没有找到，可能楼上说的是这个可以有（但还没有）😂

好的，谢谢。这个真的有点麻烦，特别产品文档输入的时候，频繁手动删除

**Comment by cweijan** [comment]
新版本已修复.

**Comment by wmkai** [comment]
> 新版本已修复.

我是3.3.0，输入中文左括号，还是会自动补全一个英文右括号，请问怎么解决呢？
