### ISSUE TITLE
现在是不支持markdown的流程图吗(例如mermaid)，希望可以添加支持

### ISSUE THREAD

**Issue by U-WHY** [cweijan/vscode-office#248]

**Comment by shelsing** [comment]
我记得以前是支持的，不知道为什么突然不行了

**Comment by shelsing** [comment]
> 我记得以前是支持的，不知道为什么突然不行了

换了个去年的版本可以显示呢

**Comment by U-WHY** [comment]
最新版本支持了

**Comment by Panlq** [comment]
<img width="507" alt="image" src="https://github.com/cweijan/vscode-office/assets/33218811/a22b9466-0c4c-4370-ad52-316d9986a1b3">

可以支持最新版的语法吗？
