### ISSUE TITLE
[BUG]代码块的主题并没有生效

### ISSUE THREAD

**Issue by U-WHY** [cweijan/vscode-office#249]
- OS:
- Extension Version:

**Comment by Autognosis** [comment]
I encountered the same BUG.
the default theme is normal，while the others are not stylished.
- OS :Windows 11;
- Extension Vesion: latest;
- VScode Version：latest；
I try to install the elder version, but also met the same BUG.

**Comment by jimmy66886** [comment]
今天打开我的也不行了，改代码块没有反应，代码块里面也没有高亮显示

**Comment by viocha** [comment]
代码主题还是不能正常显示
![image](https://github.com/cweijan/vscode-office/assets/66580331/f44794d7-e63a-45c6-ba51-dff7709b5acc)

**Comment by astronauts1** [comment]
@cweijan 作者大大，代码块主题还是不能展示

**Comment by LusterDawn** [comment]
首先必须给这个插件一个好评。
10月23号我尝试回退版本（从latest到3.0.0到2.8.x），均无法实现代码高亮。我认为原因是VScode提供的插件API发生了变动，这应该算是一个兼容性问题。

**Comment by cweijan** [comment]
主题文件是在线的, 被墙了

**Comment by U-WHY** [comment]
> 主题文件是在线的, 被墙了
我的电脑是一直开着VPN的,而且VPN走的是windows的系统代理,所以VSCODE应该能访问外网才对,另外我用浏览器访问主题文件也是正常的

**Comment by LusterDawn** [comment]
我也是，开着clash全局代理到可用的国外节点后，仍然无法实现代码高亮：
![image](https://github.com/cweijan/vscode-office/assets/83108067/7b3ffe97-61fd-44e9-8cbd-c05c597ec55c)
不过，open in vscode后弹出的markdown编辑器倒是可以代码高亮：
![image](https://github.com/cweijan/vscode-office/assets/83108067/d48e509b-36a4-4fb0-a13b-bd014df8483c)

代码高亮的实现大概是在项目的哪个文件夹？

**Comment by cweijan** [comment]
试试刚更新的3.1.8版本

**Comment by U-WHY** [comment]
> 试试刚更新的3.1.8版本

问题解决了
