### ISSUE TITLE
查看图片时有个小问题

### ISSUE THREAD

**Issue by yuhldr** [cweijan/vscode-office#25]
如果一个文件夹里有很多图片（几十上百张那种），点击右上角预览图片的按钮时，下面预览的小图片时，只能看到几行（如图一共200张图，只能看到几十张的预览图），并且这几行无法滚动

另外希望可以按照时间顺序，或者其他顺序排列图片

![image](https://user-images.githubusercontent.com/25719023/124288501-d4a95d00-db83-11eb-8828-b809129809f4.png)

**Comment by cweijan** [comment]
点这个可以隐藏预览栏, 图片多的情况建议用外部图片浏览器.
![image](https://user-images.githubusercontent.com/27798227/124391594-ea558880-dd23-11eb-8ac1-76f2de15d4ed.png)

**Comment by yuhlzu** [comment]
> 点这个可以隐藏预览栏, 图片多的情况建议用外部图片浏览器.
> ![image](https://user-images.githubusercontent.com/27798227/124391594-ea558880-dd23-11eb-8ac1-76f2de15d4ed.png)

好的，谢谢。对了，markdown和office这些能不能支持夜间模式，都是白色的，vscode主题是黑色的，看起来有些不舒服
