### ISSUE TITLE
vscodevim mode add

### ISSUE THREAD

**Issue by GladioFeng** [cweijan/vscode-office#257]
<img width="756" alt="image" src="https://github.com/cweijan/vscode-office/assets/100987925/8c378bf0-b74a-46fa-b8f5-1d7803f2eaf3">

**能增加一个类似Obsidian的Live preview vim 模式吗？**

**Comment by ShortArrow** [comment]
I feel  I wanna need too.
Vim 模式吗 is none then [only preview](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles) is enough.

**Comment by cweijan** [comment]
不会考虑支持VIM模式.
