### ISSUE TITLE
之前版本可以直接粘贴图片文件在md文件中的

### ISSUE THREAD

**Issue by IOLOII** [cweijan/vscode-office#26]
在 2.2.1 版本 可以直接粘贴图片,默认生成一个图片文件夹,后续按照md文件名对文件夹内图片分类
这个功能很好用,
但是在最近的两个版本,这个功能没有了.希望保留这个功能,目前版本已经回退到2.2.1

**Comment by cweijan** [comment]
新版确实有问题, 2.3.1版本回退了.
