### ISSUE TITLE
【需求】添加对 woff2 的支持

### ISSUE THREAD

**Issue by jerrychan7** [cweijan/vscode-office#265]
首先感谢制作者们带来这么好的插件。

能否添加对 woff2 字体文件的支持？
我看了下源码，字体的解析是依赖于 OpenType.js 的，根据[其文档](https://github.com/opentypejs/opentype.js/blob/master/README.md#loading-a-woff2-font)所说，限制其不能解析的原因是包含 woff2 解压缩器会显著增大库的体积（≈120KB => ≈1400KB），但这对 vscode 插件来说并不是一个太大的限制，只是增加了1.25MB。因此能否添加对 woff2 的支持？

Thank you guys for releasing such a good vscode plug-in.

Is it possible to add support for woff2 font files?
The parsing of fonts in this project relies on OpenType.js. According to [OpenType.js document](https://github.com/opentypejs/opentype.js/blob/master/README.md#loading-a-woff2-font), the reason why it cannot be parsed is that including the woff2 decompressor will significantly increase the size of the library (≈120KB => ≈1400KB). But increase 1.25MB is acceptable for the vscode plug-in.

**Comment by cweijan** [comment]
已在版本3.2.4支持.
