### ISSUE TITLE
[BUG]markdown无法配置使用原始的vscode编辑器进行编辑

### ISSUE THREAD

**Issue by xftxyz2001** [cweijan/vscode-office#271]
- OS:Windows 11 22H2
- Extension Version:v3.1.7

对于markdown我想使用原始的vscode编辑器，配置未生效。

bug复现：
我根据说明添加了如下配置：
```json
"workbench.editorAssociations": {
    "*.md": "default"
}
```
![image](https://github.com/cweijan/vscode-office/assets/22099765/766c7e1a-527e-43a2-9327-bbce405c3408)

此时文件正常使用默认编辑器打开：
![image](https://github.com/cweijan/vscode-office/assets/22099765/39b78469-6450-4547-b989-4e62b37aa327)

重新启动vscode后，打开markdown仍然使用默认编辑器，但是此时的`settings.json`已经被修改：
![image](https://github.com/cweijan/vscode-office/assets/22099765/fd7b13c3-c3b5-4384-9c2e-fe0227a97e40)

再次打开markdown文件后配置就失效了：
![image](https://github.com/cweijan/vscode-office/assets/22099765/0245f36a-7b6a-4c16-9a9c-141afc61d532)

**Comment by ChristopherWa20449lsh** [comment]
- OS:MacOS Montery12.6
- Extension Version:v3.1.7

@xftxyz2001 我也存在这个问题
![CleanShot 2023-10-23 at 17 35 46](https://github.com/cweijan/vscode-office/assets/138303917/e8f7f359-4402-4512-bc24-795d0abc86e1)

**Comment by ChristopherWa20449lsh** [comment]
@xftxyz2001 知道原因了，是Vscode本身的问题（即使把插件卸载，在"workbench.editorAssociations"中添加的default关联依然会被默认的编辑器设置删除）-> https://github.com/microsoft/vscode/issues/99172

而且貌似officeViewer这个插件会默认隐式绑定所有支持的文件类型，这和之前Vscode的机制结合也就导致了添加default不生效的问题

如果想兼容，个人解决方案是在工作区设置里添加👇🏻

```json
"workbench.editorAssociations": {
    "*.md": "default"
}
```
_不过每个工作区都要添加好麻烦所以我还是直接把插件卸了hh_

**Comment by xftxyz2001** [comment]
@ChristopherWa20449lsh  我目前是这样解决的（尽管这有些怪）
```json
"workbench.editorAssociations": {
    "*md": "default"
}
```
如果设置成这样就不会被清除。

**Comment by YuruiHong** [comment]
可以修改插件目录下的`package.json`达到全局解决的效果：

https://github.com/cweijan/vscode-office/blob/12561ada9683bf5b362c0fd26f10edf0363d258c/package.json#L396-L402

删除`selector`内的`{"filenamePattern": "*.md"}`即可。

P.S. 我不熟悉VS Code插件开发，但想问问是否有对`selector`提供配置功能的可能？定位并修改相关源码毕竟比较麻烦，而且更新后需要重新修改。

**Comment by ChristopherWa20449lsh** [comment]
其实只要配置一下文件的默认打开方式就好啦，最近把插件下回来又出现这个问题突然右键试了下就行了（也不会出现重新打开配置文件被修改的问题）
![CleanShot 2024-06-15 at 15 44 18](https://github.com/cweijan/vscode-office/assets/138303917/4fbee0ba-6ec6-4213-9c4c-dd540ec26180)

**Comment by xftxyz2001** [comment]
> 其实只要配置一下文件的默认打开方式就好啦，最近把插件下回来又出现这个问题突然右键试了下就行了（也不会出现重新打开配置文件被修改的问题） ![CleanShot 2024-06-15 at 15 44 18](https://private-user-images.githubusercontent.com/138303917/339965004-4fbee0ba-6ec6-4213-9c4c-dd540ec26180.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzgxNzcsIm5iZiI6MTcxODQzNzg3NywicGF0aCI6Ii8xMzgzMDM5MTcvMzM5OTY1MDA0LTRmYmVlMGJhLTZlYzYtNDIxMy05YzRjLWRkNTQwZWMyNjE4MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNzUxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzczNGExNjU3ZDgwMTllODU1ZTVlNGE3MDY2ZmZkOTU5NWQ1NjA4NTUxYjRiMTM2ODA4MWJjYTE4ZTEzMTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42GaACZXaMBGofXzQew68H3-imW3b8fuLUOfM0Yf8eI) [ ![CleanShot 2024-06-15 at 15 44 18](https://private-user-images.githubusercontent.com/138303917/339965004-4fbee0ba-6ec6-4213-9c4c-dd540ec26180.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzgxNzcsIm5iZiI6MTcxODQzNzg3NywicGF0aCI6Ii8xMzgzMDM5MTcvMzM5OTY1MDA0LTRmYmVlMGJhLTZlYzYtNDIxMy05YzRjLWRkNTQwZWMyNjE4MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNzUxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzczNGExNjU3ZDgwMTllODU1ZTVlNGE3MDY2ZmZkOTU5NWQ1NjA4NTUxYjRiMTM2ODA4MWJjYTE4ZTEzMTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42GaACZXaMBGofXzQew68H3-imW3b8fuLUOfM0Yf8eI) ](https://private-user-images.githubusercontent.com/138303917/339965004-4fbee0ba-6ec6-4213-9c4c-dd540ec26180.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzgxNzcsIm5iZiI6MTcxODQzNzg3NywicGF0aCI6Ii8xMzgzMDM5MTcvMzM5OTY1MDA0LTRmYmVlMGJhLTZlYzYtNDIxMy05YzRjLWRkNTQwZWMyNjE4MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNzUxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzczNGExNjU3ZDgwMTllODU1ZTVlNGE3MDY2ZmZkOTU5NWQ1NjA4NTUxYjRiMTM2ODA4MWJjYTE4ZTEzMTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42GaACZXaMBGofXzQew68H3-imW3b8fuLUOfM0Yf8eI) [ ](https://private-user-images.githubusercontent.com/138303917/339965004-4fbee0ba-6ec6-4213-9c4c-dd540ec26180.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzgxNzcsIm5iZiI6MTcxODQzNzg3NywicGF0aCI6Ii8xMzgzMDM5MTcvMzM5OTY1MDA0LTRmYmVlMGJhLTZlYzYtNDIxMy05YzRjLWRkNTQwZWMyNjE4MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNzUxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzczNGExNjU3ZDgwMTllODU1ZTVlNGE3MDY2ZmZkOTU5NWQ1NjA4NTUxYjRiMTM2ODA4MWJjYTE4ZTEzMTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.42GaACZXaMBGofXzQew68H3-imW3b8fuLUOfM0Yf8eI)

之前这样是不行的，不过现在看起来bug已经修好了。
