### ISSUE TITLE
[BUG] 按指定步骤在全局搜索+文件内搜索时切换markdown文档, vscode发生崩溃

### ISSUE THREAD

**Issue by imxys** [cweijan/vscode-office#274]
- OS: Ubuntu 22.04.3
- Extension Version: v3.1.8
- vscode:
```
版本: 1.83.1
提交: f1b07bd25dfad64b0167beb15359ae573aecd2cc
日期: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-87-generic
```
复现步骤
1. 打开vscode
2. 打开全局搜索,搜索出markdown文档, 多份; 此时在不同markdown文档直接切换不会有问题(默认使用本插件Office Viewer打开)
3. 在某个markdown文档内打开搜索(ctrl+f), 输入可搜索到的字符串, 可以上下选择
4. 在全局搜索框内切换到另一份文档, 单击切换(我没双击固定标签)
5. 崩溃, 概率大概能有90%, 感觉按照操作来几乎都崩溃了
6. 如果是在标签栏里切换到另一份文档, 似乎是不容易崩溃的

**Comment by cweijan** [comment]
还真会崩溃🤣, 但这个是VS Code的Bug, 我干涉不了.
