### ISSUE TITLE
怎么在default模式下进入这个插件的渲染界面

### ISSUE THREAD

**Issue by zhiyanzhaijie** [cweijan/vscode-office#275]
# 问题描述  
我知道安装这个插件后，选中`.md`等文件时会自动调用插件打开。但是，现在我按照插件市场说明所做，在`settings.json`下设置了`"*.md": "default"`后，我完全不知道要如何手动使用这个插件打开`.md`了。

我没有找到手动打开的功能。这种情况下，这个插件装不装都一样了，就只是一个占内存的东西。
如果确实有手动打开的功能，请把它放在更显眼的地方。

**Comment by zhiyanzhaijie** [comment]
问题总在提出后被快速解决，我现在发现了：
可以在**Explorer**中右击`.md`等文件，选择`Open With`, 选择`Typora`就可以了。
--- 
但是，能否像`Code Runner`那样，直接在编辑区右上角新增一个图标跳转进入呢？

**Comment by cweijan** [comment]
已在新版本增加图标用于快速切换.
<img width="670" alt="image" src="https://github.com/cweijan/vscode-office/assets/27798227/fc9bb3ef-8abc-4858-b850-76661ca45b73">
