### ISSUE TITLE
[BUG] Can NOT display correctly in the DIFF view.

### ISSUE THREAD

**Issue by Nigh** [cweijan/vscode-office#279]
- OS: Windows 11 22H2
- Extension Version: v3.1.8

I think the markdown view should be disabled in the DIFF view.

**Comment by Vigilans** [comment]
Ref https://github.com/cweijan/vscode-office/issues/183#issuecomment-1879592003:

> According to https://github.com/microsoft/vscode/issues/138525#issuecomment-1847679100, diff editor has its own resource url `git:/...` or `gitlens:/...`, so can be specified to use default editor view in `workbench.editorAssociations`:
> 
> ```json
>     "workbench.editorAssociations": {
>         "{git,gitlens}:/**/*.{md,csv}": "default"
>     },
> ```
> 
> As such `vscode-office`'s rendering is disabled in diff view.
> 
> **NOTE**: Due to a bug in vscode: [editorResolverService.ts#L166-L181](https://github.com/microsoft/vscode/blob/f88bce8fe6a6d2ccd27cbd64bb26853cd8779afa/src/vs/workbench/services/editor/browser/editorResolverService.ts#L166-L181), specifying different editor type for normal view and diff view will make both page in diff view regress into default view. This is because in diff view, left side url is `git:/...`, while right side url is actually `file:/...`.

**Comment by cweijan** [comment]
Fixed in version 3.2.0.
