### ISSUE TITLE
如何切换到源码编辑类似Typora的Ctrl+/这种快捷键

### ISSUE THREAD

**Issue by Juuen** [cweijan/vscode-office#28]
因为有些特殊场景没有源码编辑来的利索，希望有可能两种视图可以有切换的地方。

**Comment by cweijan** [comment]
点这个按钮就可以哦.
![image](https://user-images.githubusercontent.com/27798227/128601668-07bbb80e-6a0a-435d-a2da-430f876d89a8.png)

**Comment by lornally** [comment]
为啥我这里没有这个按钮?

**Comment by cweijan** [comment]
@lornally 
装这个插件 https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office

**Comment by lornally** [comment]
谢谢哈.

**Comment by quanru** [comment]
> 点这个按钮就可以哦. ![image](https://user-images.githubusercontent.com/27798227/128601668-07bbb80e-6a0a-435d-a2da-430f876d89a8.png)

这个能有快捷键吗？

**Comment by cweijan** [comment]
新版本点击按钮后可以同步编辑了

**Comment by zhaoqingqing** [comment]
@cweijan 可以给这个按钮加个快捷键么？还有个问题就是不能粘贴为纯文本？在vditor的论坛也没找到这项【粘贴为纯文本】

**Comment by firerflystar** [comment]
shortcut 设置 搜 view: toggle editor type
