### ISSUE TITLE
希望可以有按钮可以把markdown的编辑器侧栏（目录）隐藏/显示

### ISSUE THREAD

**Issue by JordanQD** [cweijan/vscode-office#281]
如题，一直显示有点占地方

**Comment by wywzxxz** [comment]
已经有了，参考issue:https://github.com/cweijan/vscode-office/issues/20

或者更简单点：
![image](https://github.com/cweijan/vscode-office/assets/5335612/c3693b0e-730e-4075-b5cf-2ffad155f6e3)

**Comment by JordanQD** [comment]
> 已经有了，参考issue:#20
> 
> 或者更简单点： ![image](https://private-user-images.githubusercontent.com/5335612/292761611-c3693b0e-730e-4075-b5cf-2ffad155f6e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzY1NDEsIm5iZiI6MTcwMzU3NjI0MSwicGF0aCI6Ii81MzM1NjEyLzI5Mjc2MTYxMS1jMzY5M2IwZS03MzBlLTQwNzUtYjVjZi0yZmZhZDE1NWY2ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDczNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDYxZDBhMWZmZTMyYmNmYTQzYTA5MWNkNzBkOWRjNGIxYjg1YzExN2U1ZTQxZjU3OGY2ZGY5Mjg1MThhY2RhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JHpejNvzL4diGIAdbhLtgPqF9vRZuHcSR4hBxwcBe_U)

这么抽象的图标么😂 好的 谢谢你
