### ISSUE TITLE
[BUG] keyboard shortcuts not work for headings

### ISSUE THREAD

**Issue by z06gjp4** [cweijan/vscode-office#302]
- OS: ubuntu 22.04
- Extension Version:v3.2.5
- vscode Version: 1.87.1
it（alt+ctrl+1 for heading 1） work in for vscode Version:1.84.1，can you check it？

**Comment by cweijan** [comment]
I don't have an Ubuntu Desktop device, but this shortcut key works fine on my Windows, I think maybe the shortcut key is occupied by other software.

**Comment by cweijan** [comment]
I don't have an Ubuntu Desktop device, but this shortcut key works fine on my Windows, I think maybe the shortcut key is occupied by other software.
