### ISSUE TITLE
建议自动识别<br>为换行而不是代码

### ISSUE THREAD

**Issue by DuckDuckStudio** [cweijan/vscode-office#310]
在使用这个扩展对我之前的Markdown文件进行编辑时，会自动把我之前的Markdown中的用于换行（没有带反引号的）的`<br>`自动转换为带有反引号的代码`<br>`，这导致了我的文档多次离奇缺失换行（如果使用两个空格作为换行，在使用扩展界面编辑时也会离奇消失）
例如这个README，我编辑了好几次都会离奇出现换行问题：
![屏幕截图 2024-04-28 134013](https://github.com/cweijan/vscode-office/assets/89643991/6cbc336d-dc23-41ee-8f43-7a1f45f13ed8)
我修改了很多次但还是会出现换行离奇消失的问题...所以我在部分时候不得不禁用扩展。
![image](https://github.com/cweijan/vscode-office/assets/89643991/acd57a43-be6c-4537-9f99-97f1167f61ba)

**Comment by cweijan** [comment]
建议使用两个空行来替代br, 这是vditor的bug

**Comment by DuckDuckStudio** [comment]
该问题似乎不会被修正...
相关Issues:
[Vanessa219/vditor #1624](https://github.com/Vanessa219/vditor/issues/1624)
[Vanessa219/vditor #1333](https://github.com/Vanessa219/vditor/issues/1333)
