### ISSUE TITLE
打开 md 文件时，默认预览功能

### ISSUE THREAD

**Issue by Yang-yibu** [cweijan/vscode-office#313]
添加全局配置，打开 md 文件时，默认显示预览模式还是编辑模式

![image](https://github.com/cweijan/vscode-office/assets/23130670/db8342ed-42a6-450b-831b-c5d77e861322)

**Comment by cweijan** [comment]
英文readme有说明.

**Comment by Yang-yibu** [comment]
如果你只的是这个配置，那跟我说的不是一个意思
{
    "workbench.editorAssociations": {
        "*.md": "default"
    }
}

我的意思是可以配置开启 preview 模式
![image](https://github.com/cweijan/vscode-office/assets/23130670/2db408cb-368f-4475-b5e9-95eaeb94d83b)
