### ISSUE TITLE
[BUG] 长时间打开md文件会卡死无法编辑

### ISSUE THREAD

**Issue by mcl44** [cweijan/vscode-office#320]
- OS: Windows 11 build 22000.0
- Extension Version: 3.2.9
- 如题所述，源文件可以正常编辑，vditor我也试过了也没有问题。但是插件就会这样，大概打开十多分钟就会卡死，像是和文件失去连接了(文件指针丢失？)

**Comment by cweijan** [comment]
VS Code问题, 和该扩展无关.
