### ISSUE TITLE
[BUG]反馈第一个bug，加粗内容有正反中括号时，预览会不对

### ISSUE THREAD

**Issue by XiaoChen-Me** [cweijan/vscode-office#326]
- OS: windows 10 pro
- Extension Version: 3.3.6 
虽然是个小bug，但看着难受，我经常加粗中括号内容
如题，加粗内容有正反中扩号时，预览会不加粗，前后显示两个*号
初步猜测是因为没有转义符号
中英文全半角中括号都会这样
图例使用的是中文全角符号
![image](https://github.com/cweijan/vscode-office/assets/173120921/0bd8a9d1-8d2a-48d9-8dda-c0e7815d60bc)

**Comment by cweijan** [comment]
这些都是Vdtiror的bug, 无计划处理.
