### ISSUE TITLE
[BUG]反馈第五个bug，部分常用html标签预览异常

### ISSUE THREAD

**Issue by XiaoChen-Me** [cweijan/vscode-office#332]
- OS:略
- Extension Version:337

插件似乎支持了部分html标签，如居中 换行 下划线等。
但有部分常用标签未受到支持，无法正常预览
如上下标标签`<sup>` `<sub> `，按键标签`<kbd> `等。

此类标签将会预览成行内代码
![image](https://github.com/user-attachments/assets/20a5289d-a71d-4c3c-aa1f-6d0a37b7ea28)

**Comment by irvnriir** [comment]
Idk whether its related to this Issue, but i still can't use `<sup>` in the Markdown editor on 3.3.10.

See https://github.com/Vanessa219/vditor/issues/1647 .
