### ISSUE TITLE
[BUG]反馈第八个bug，删除键时列表动作不确定，有时是删除前置序号，有时是降级

### ISSUE THREAD

**Issue by XiaoChen-Me** [cweijan/vscode-office#335]
- OS:win10pro
- Extension Version:337
如图，此时在文末的二级序号处点击backspace键
![image](https://github.com/user-attachments/assets/9fbd4406-f834-4fc7-90f5-43c37c5e552c)

这时动作不确定，有可能是不降级、只删除·序号；也可能是降级为一级序号。
个人意见是删除键动作是删除序号就好，升降级用tab键、shift+tab键。
更何况连续enter键也是降级，删除键降级有些多余

**Comment by Alex-SYZ1** [comment]
居然连续按enter降级。。。，我整了半天这个反向缩进，shift tab没反应都。
连按enter解决了谢谢
