### ISSUE TITLE
[BUG] officeviwer会修改xlsx的格式吗

### ISSUE THREAD

**Issue by chenzhiqiang1** [cweijan/vscode-office#338]
- OS: windows
- Extension Version: 3.1.8
在officeviwer里面保存xlsx文件，是不是把xlsx格式给破坏了？我在用其他语言读取这个修改后的文件时，读取出的结果为空。

**Comment by XiaoChen-Me** [comment]
318版本有点久了吧，，试试最新版

**Comment by cweijan** [comment]
保存时会清除所有单元格格式, 最新版已移除xlsx编辑功能.
