### ISSUE TITLE
这是一个伟大的插件, 如果安装说明说一下, 需要打开配置中的跟随系统theme就更好了

### ISSUE THREAD

**Issue by lornally** [cweijan/vscode-office#34]
因为, one dark modern不起作用 , 我反复安装卸载, 还重启了机器, 直到来这里, 才看到, 要打开配置中的 : 

设置里面, 选择:Viewer follow vscode theme, 配置:  "vscode-office.autoTheme": true

如果咱们那个精简的安装主页面, 说一下这个就好了, 咱们插件安装的主页(detail)啥都没说......

**Comment by cweijan** [comment]
已在文档说明
