### ISSUE TITLE
Version [3.3.11] Shows .xlsx blank sheets!

### ISSUE THREAD

**Issue by Basselfathy** [cweijan/vscode-office#352]
- OS: Windows 11
- Extension Version: v3.3.11

**Version 3.3.10**
![V3 3 10](https://github.com/user-attachments/assets/281026bd-4ecd-4f34-88c8-3f71248a4445)

**Version 3.3.11**
![V3 3 11](https://github.com/user-attachments/assets/7f2a9c6b-7e1b-4dea-a6a8-1a9b7c91efcd)

**Comment by longfei8533** [comment]
![image](https://github.com/user-attachments/assets/a56433b1-09cc-425d-b347-1a8653f08784)
CSV file shows blank

**Comment by Doradx** [comment]
mee too.
the same problem.

**Comment by szw0407** [comment]
Same problem, falling back to the previous version.

**Comment by Lord-Fec** [comment]
me too!

**Comment by its-snj** [comment]
me too! .csv file is also blank!!

**Comment by Puliczek** [comment]
Thanks, downgraded to Version 3.3.10. And works now :)

**Comment by Lord-Fec** [comment]
Updating to 3.4.1 seems to fix this bug.

**Comment by CodeEagle** [comment]
not work as well, macOS,3.4.1.xls file
