### ISSUE TITLE
[BUG] readme does not display anything after using 3.4.4

### ISSUE THREAD

**Issue by Puiching-Memory** [cweijan/vscode-office#370]
- OS:
windows11
- Extension Version:
3.4.4

After updating to 3.4.4, viewing any readme will not be displayed.
I don't know much about how vscode plugins work, so I can't provide an error report. But if you can guide me, I have my full support.

**Comment by noace1** [comment]
Yes, I just encountered the same problem. Restarting vscode couldn't solve it, but it was all fine just an hour ago.

**Comment by noace1** [comment]
Yes, I just encountered the same problem. Restarting vscode couldn't solve it, but it was all fine just an hour ago.

**Comment by ilovecxty** [comment]
In Plugin-Enabled, right click on plugin, you can find a "choose specific version", roll back to 3.4.3, this version can work
<img width="268" alt="image" src="https://github.com/user-attachments/assets/e5347c74-99aa-4110-ad1e-2032f0c3abf2">

**Comment by ilovecxty** [comment]
I have tried opening other supported file types, including PDF, CSV, XLSX, and DOCX, but none of them can be opened. It seems there is an issue with the page rendering, as no interface can be accessed.
I suspect that a piece of common code has error, causing all supported files are fail to open, and the page remains in a loading state.

我尝试了其他支持的文件，包括pdf,csv,xlsx,docx，都无法打开，似乎是页面渲染出了问题，无法打开任何界面。
我猜是某一个通用的代码坏了，所有支持的文件都无法打开了，页面一直在加载。

**Comment by Attack825** [comment]
I've run into the same problem after updating to version 3.4.4.

**Comment by daishengda2018** [comment]
> * OS:
>   windows11
> * Extension Version:
>   3.4.4
> 
> After updating to 3.4.4, viewing any readme will not be displayed. I don't know much about how vscode plugins work, so I can't provide an error report. But if you can guide me, I have my full support.

Same problem. After re-install 3.4.3,  it's working.
![image](https://github.com/user-attachments/assets/7a56fc00-ccd2-429a-aa36-7f8f0ad214e2)

**Comment by Jeromestein** [comment]
> In Plugin-Enabled, right click on plugin, you can find a "choose specific version", roll back to 3.4.3, this version can work <img alt="image" width="268" src="https://private-user-images.githubusercontent.com/70325048/390251415-e5347c74-99aa-4110-ad1e-2032f0c3abf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTM5NTUsIm5iZiI6MTczMjc1MzY1NSwicGF0aCI6Ii83MDMyNTA0OC8zOTAyNTE0MTUtZTUzNDdjNzQtOTlhYS00MTEwLWFkMWUtMjAzMmYwYzNhYmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAwMjczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YzBhMjdmZDRlZjc3YzYyZmQ2MTdlMmU5NmZjZjAwZWQ2NzIzNjFmMWFlMzkwMzEyM2NmYTMyOTQ4OThmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7655t5YEn2LotblUXXdGIkUBWcc_XOIWqHxN-_vYT5o">

牛的
W！

**Comment by liu-yucheng** [comment]
Exactly the same issue += 1.

**Comment by Puiching-Memory** [comment]
The current issue encountered the same problem:
https://github.com/cweijan/vscode-office/issues/376
https://github.com/cweijan/vscode-office/issues/374
https://github.com/cweijan/vscode-office/issues/373
https://github.com/cweijan/vscode-office/issues/372

This is due to the 3.4.4 update, falling back to 3.4.3 avoids this issue for now. But I think the maintainer should start investigating the cause as soon as possible.It could be an error caused by a change in a key dependency item.

By comparing the file differences between 3.4.3 and 3.4.4, I think we should focus on the following files:
https://github.com/cweijan/vscode-office/blob/7aabca97eac3dd2c4666fd59a7c0c59715701ae3/package.json#L627-L658

![image](https://github.com/user-attachments/assets/94494fc0-695b-42e5-923d-9556a9bab92c)
Part of the difference may be due to the accompanying dependency file changes, the source of which is not found in the source code.

Does anyone have any comment on that? I don't know about javasprint development

**Comment by cweijan** [comment]
Fixed in version 3.4.5.
