### ISSUE TITLE
[BUG] command 'office.markdown.paste' not found

### ISSUE THREAD

**Issue by zengyijian916** [cweijan/vscode-office#371]
- OS: windows 11
- Extension Version: latest version

After update to the latest version automaticly.
can not paste in markdown file and will show "command 'office.markdown.paste' not found".

**Comment by System2c** [comment]
yeah, I also encounter the same problem. I install 3.4.3 Office Viewer temporarily until the bug is fixed.

**Comment by li-cr** [comment]
go back version.

**Comment by liu-yucheng** [comment]
Exactly the same issue += 1.

**Comment by Achuan-2** [comment]
+1

**Comment by jamesdeluk** [comment]
Same. Workarounds include changing the Language Mode away from Markdown, or selecting existing text and pasting over it.

**Comment by Cateds** [comment]
exactly the same issue++

**Comment by EAGLEEEEEE** [comment]
Same Problem. I disabled the extension "Office Viewer" and the bug is fixed.

**Comment by cweijan** [comment]
Fixed in version 3.4.5.
