### ISSUE TITLE
[BUG] no appearance of anything in the edition window

### ISSUE THREAD

**Issue by patinusb** [cweijan/vscode-office#372]
- OS: windows 11
- Extension Version: 3.4.4
- Since today, editor is not able to open markdown files for edition. Screen is blank andd nothing appears.

**Comment by geminigeek** [comment]
+1 same, nothing empty

**Comment by Jeromestein** [comment]
- OS: Mac OS 15.1.1 (M1 Pro)
- Extension Version: 3.4.4
- Same here, since at least 2 hours ago, the vscode and cursor cannnot open .md files. 
- UI shows it is loading all the time.
- It can be opened when I choose Open With Text Edit (Build-in).

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/64426c36-3d2b-4dce-af32-710238f29944">

**Comment by PhilCoulson** [comment]
same problem.
- OS: win11
- Extension : v3.4.4

Disable automatic update and manually revert to v3.4.3 works properly.

**Comment by 0x3a0x29** [comment]
- OS: win11
- Extension: v3.4.4
I have same problem,when I revert to older version ,it works.

**Comment by EsqerYasen** [comment]
I installed previous version than this problem is fixed. 
![image](https://github.com/user-attachments/assets/7a55a784-4595-4461-83b8-7440076afb74)

**Comment by qvoid** [comment]
Same problem here.
OS: Ubuntu 22.04
Extension: v3.4.4

**Comment by P-MCC** [comment]
Same issue here 
As @PhilCoulson and other programmers mentioned by disabling auto update and reverting to the previous version of the extension the issue has been solved for me on Windows 10 os.
![office Viewer](https://github.com/user-attachments/assets/47e53e87-0ae2-4f81-9570-fad798621fe4)

**Comment by liu-yucheng** [comment]
Exactly the same issue += 1.

**Comment by DoWhileFR** [comment]
Same issue

**Comment by Y3y1ng** [comment]
+1

**Comment by anandakevin** [comment]
I had same issue. fixed by rolling back to v3.4.3 on windows 11

**Comment by ivyquartz** [comment]
+=1
- OS: Windows 11 Pro 10.0.22531 (Build 22631)
- Architecture: 64-bit
- VSCode version: 1.95.3
- Extension version: v3.4.4

Not a big issue since I was also able to fix it by rolling back to v3.4.3

**Comment by cweijan** [comment]
Fixed in version 3.4.5.
