### ISSUE TITLE
[BUG] 11月28号更新后无法使用

### ISSUE THREAD

**Issue by liangweidonggood** [cweijan/vscode-office#373]
- OS: win10
- Extension Version: 3.4.4
![image](https://github.com/user-attachments/assets/80131f4f-0410-486a-85d8-3b8305874c7d)

**Comment by liangweidonggood** [comment]
安装特定版本后能正常使用,3.4.3

**Comment by peng84** [comment]
I'm having this issue as well

**Comment by peng84** [comment]
我也出现了这个问题

**Comment by zyl9737** [comment]
OS：Ubuntu 22.04
Extension Version: 3.4.4
也加载不出来

**Comment by liu-yucheng** [comment]
遇到完全相同的问题 += 1.

**Comment by JIANG-Wu-19** [comment]
+1

**Comment by JIANG-Wu-19** [comment]
i delete all extensions about md, and finnal locate the office viewer

> +1

**Comment by JIANG-Wu-19** [comment]
> 安装特定版本后能正常使用,3.4.3

尝试了这种方法，ok了

**Comment by cweijan** [comment]
Fixed in version 3.4.5.
