### ISSUE TITLE
[BUG]自动更新至最新版无法正常使用

### ISSUE THREAD

**Issue by SeanDictionary** [cweijan/vscode-office#374]
- OS: win10
- Extension Version: V3.4.4

首先是md文件打卡一直加载无法正常打开，之后再次尝试发现能成功打开，但可视化编辑用不了，报错`command 'office.markdown.switch' not found`

ps.除上述严重bug外还有其余bug，在复制文本后，在vscode内尝试粘贴时会无法粘贴，报错'command 'office.markdown.paste' not found'

## 目前解决方法
回退至版本V3.4.3，即可正常使用

**Comment by Yuelioi** [comment]
同样 最新版无法使用

**Comment by zhch25** [comment]
3.4.4中csv文件无法预览，回退至版本3.4.3可正常预览

**Comment by FyingChu** [comment]
I encounter the same issue...

**Comment by Rayaray** [comment]
同样问题，已经退回3.4.3.

**Comment by cweijan** [comment]
Fixed in version 3.4.5.
