### ISSUE TITLE
[BUG] Paste (Ctrl + V) Command not working

### ISSUE THREAD

**Issue by tnakaicode** [cweijan/vscode-office#375]
- OS: WIn10
- Extension Version: V3.4.4

Since Copy and Paste's Paste (Ctrl + V) stopped working, I looked it up in ```Developer: Toggle Screencast Mode```, and found that the command overlapped with the Keyboard Bind ```Enhance pater in markdown```.
I don't know what ```Enhance pater in markdown``` is intended for, but I think it's better to lower the priority because the Paste operation is more basic.

**Comment by ivyquartz** [comment]
+=1
- OS: Windows 11 Pro 10.0.22531 (Build 22631)
- Architecture: 64-bit
- VSCode version: 1.95.3
- Extension version: v3.4.4

Not a big issue since I was able to fix it by rolling back to v3.4.3

**Comment by cweijan** [comment]
Fixed in version 3.4.5.
