### ISSUE TITLE
[BUG] All Word file's preview not working

### ISSUE THREAD

**Issue by tnakaicode** [cweijan/vscode-office#376]
- OS: Win10
- Extension Version: V3.4.4
- VSCode: 1.95.3

The preview for Word files (*.docx, *.xlsx, *.pdf) and Image files (*.png, *.jpg, ...) is not working.
I remember this happening when I updated VSCode.

**Comment by SeanDictionary** [comment]
> * OS: Win10
> * Extension Version: V3.4.4
> * VSCode: 1.95.3
> 
> The preview for Word files (*.docx, *.xlsx, _.pdf) and Image files (_.png, *.jpg, ...) is not working. I remember this happening when I updated VSCode.

the error is caused by the latest version V3.4.4.The current solution is rollback version V3.4.3 and turn off the auto-update

**Comment by ducminh25** [comment]
Actually, opening, previewing file is not working at the current update. Roll back to the very previous one would help/

**Comment by zhch25** [comment]
The preview for .csv file is not working too,Roll back to v3.4.3 can preview .csv file

**Comment by jiuyueshenhua** [comment]
me tool.
![image](https://github.com/user-attachments/assets/96025444-d15f-48f5-ab34-0cb399b60f39)

**Comment by cweijan** [comment]
Fixed in version 3.4.5.
