### ISSUE TITLE
Open-vsx extension is outdated

### ISSUE THREAD

**Issue by pm4rcin** [cweijan/vscode-office#4]
Hi, [open-vsx](https://open-vsx.org/extension/cweijan/vscode-office) extension for vscodium is outdated. Could you update it?

**Comment by cweijan** [comment]
Newest version has been upload.

**Comment by pm4rcin** [comment]
Hi, could you update extension again? Also there's a way to automatically upload to open-vsx. [Here's](https://github.com/muhammadsammy/free-omnisharp-vscode/tree/master/.github/workflows) an example project that use it.
