### ISSUE TITLE
请问如何自定义css以个性化预览

### ISSUE THREAD

**Issue by howie6879** [cweijan/vscode-office#40]
@cweijan 作者你好：

非常感谢你开源的这款插件，让我在vscode上有了类似typora的协作体验，感激不尽。

这里有个小问题，请问如何自定义css来进行个性化预览，类似Typora将css文件放到相关目录，支持各种自定义主题。

**Comment by ljk5403** [comment]
同求，很好的一个功能。

**Comment by cweijan** [comment]
可以将这个文件里面的css替换
C:\Users\{你的账户名}\.vscode-server\extensions\cweijan.vscode-office-2.4.2\resource\vditor\index.css

**Comment by ljk5403** [comment]
> 可以将这个文件里面的css替换 C:\Users{你的账户名}.vscode-server\extensions\cweijan.vscode-office-2.4.2\resource\vditor\index.css

谢谢您！
如果方便的话其实可以考虑把css做成可切换的选项，个人觉得这个功能还挺好用的（当然得看作者大大是否感兴趣啦）
