### ISSUE TITLE
Markdown所见即所得编辑器中按下Tab使其缩进的实现与其实际行为有出入

### ISSUE THREAD

**Issue by HeartyYF** [cweijan/vscode-office#46]
在某行的行首按下Tab后，看上去像是在行首有四字符的缩进，但实际在源文件里是以类似代码块的三个`围起来的。重新加载之后就会显示成代码块的样式，缩进就没了。

**Comment by cweijan** [comment]
问题产生的原因找到了, 等待作者反馈
88250/lute#162
---
最新版本已修复了
