### ISSUE TITLE
Pasted images are placed in a visible folder

### ISSUE THREAD

**Issue by DennisL68** [cweijan/vscode-office#50]
When pasting an image to a markdown document, the image is saved to `image/<filename>/<hash>.png`
That folder will be visible in a git based wiki as used in MS DevOps Server if not hidden using a dot as in `.image/<filename>/<hash>.png`

Please change the default folder named for pasted images.
Or provide a way to change the default folder in the settings.

**Comment by cweijan** [comment]
The image path can be configured in the latest version.
![image](https://user-images.githubusercontent.com/27798227/172294779-873f1de4-a2c8-4a43-8aa6-d5522ec63efe.png)
