### ISSUE TITLE
对vscode里新建的MD文件无效

### ISSUE THREAD

**Issue by forrestgao** [cweijan/vscode-office#51]
只有已保存的md文件重新打开时才会生效
如果在vsc中新建一个md文件则无效
这个是普遍情况吗？

**Comment by cweijan** [comment]
不会的, 你操作有问题把.

**Comment by forrestgao** [comment]
准确的说是只有打开已旧md文件或在VSC左侧资源管理中新建文件然后打开才会出现，菜单栏新建文件或直接双击创建的文件则无效

**Comment by forrestgao** [comment]
准确的说是只有打开已旧md文件或在VSC左侧资源管理中新建文件然后打开才会出现，菜单栏新建文件或直接双击创建的文件则无效

**Comment by forrestgao** [comment]
准确的说是只有打开已旧md文件或在VSC左侧资源管理中新建文件然后打开才会出现，菜单栏新建文件或直接双击创建的文件则无效

**Comment by cweijan** [comment]
我是不会的, 录了个图, 你检查下你的vscode设置.
![8y71x-jkqza](https://user-images.githubusercontent.com/27798227/148507956-68bace44-de01-45ed-ae14-52e011abaaa5.gif)
