### ISSUE TITLE
请问是否可以添加上下左右移动的快捷键？

### ISSUE THREAD

**Issue by wuse94** [cweijan/vscode-office#56]
请问是否可以添加上下左右移动的快捷键？可以方便在编辑的时候移动光标不需要离开主键盘，感谢~

**Comment by cweijan** [comment]
没有这个计划呢, 我个人是使用autohotkey进行按键映射达到这个效果的.
https://wyagd001.github.io/zh-cn/docs/Program.htm

**Comment by wuse94** [comment]
> 没有这个计划呢, 我个人是使用autohotkey进行按键映射达到这个效果的. https://wyagd001.github.io/zh-cn/docs/Program.htm

感谢，我去了解一下～

**Comment by cweijan** [comment]
安装autohotkey后, 创建ahk后缀的文件, 然后将编写脚本后就可以运行了, 只支持windows, 给你一个参考的示例.
```autohotkey
#SingleInstance force
#MenuMaskKey vk07 
#MaxHotkeysPerInterval 200

; 将ctrl+i映射为上, ctrl+j映射为下
^i::SendInput {up}
^j::SendInput {down}
^;::Send {left}
^'::Send {right}

; 当exe的名称为code.exe时才生效
#IfWinActive AHK_exe Code.exe
    ^i::SendInput {up}
    ^j::SendInput {down}
    ^;::Send {left}
    ^'::Send {right}
#IfWinActive
```
