### ISSUE TITLE
[feature request] choose between source and gui for csv files

### ISSUE THREAD

**Issue by ccoenen** [cweijan/vscode-office#6]
I love the spreadsheet view for csv-files, but sometimes I do need the power of the raw text editor. For example to do a multi-cursor edit or when I search&replace with a complex regex. Also I like to check the exact underlying csv format every now and then (comma vs semi-colon, double quotes vs single quotes and things like that).

I would like to be able wo easily switch between spreadsheet view from this plugin and the regular text editor from vscode/codium. Currently my workaround is to rename the file to `.txt` but that's something would like to avoid.

**Comment by cweijan** [comment]
Right click file and choose text editor.
![image](https://user-images.githubusercontent.com/27798227/114554748-a2c9de00-9c99-11eb-9b4b-0f879b23796e.png)

**Comment by ccoenen** [comment]
Nice! I did not know this existed :-)

Thank you! Consider this done.
