### ISSUE TITLE
代码块鼠标选中,就会多出一份,非常影响查看

### ISSUE THREAD

**Issue by kinloonglee** [cweijan/vscode-office#60]
![image](https://user-images.githubusercontent.com/30849180/151599007-f5255178-7e1c-442b-bc9b-576705efd65d.png)

为什么一选中代码块, 就变成两份, 一两行代码还好,  几十行,让人看的眼花缭乱.

**Comment by DingYizhi** [comment]
+1 希望能改进

**Comment by cweijan** [comment]
vditor就是这样设计的, 确实不好操作, 但没办法.

**Comment by cweijan** [comment]
Hi, 发布了2.6.7版本, 现在可以关闭代码预览, 点击代码块后不会变成两份, 但是无法高亮.
![image](https://user-images.githubusercontent.com/27798227/187055280-edfd5aff-b599-4fbf-ad49-5d90724de3ac.png)

**Comment by Achuan-2** [comment]
> vditor就是这样设计的, 确实不好操作, 但没办法.

思源笔记之前基于Vditor改进过代码块编辑，可惜两位开发者忙于开发思源笔记，没空把代码整理到Vditor里
