### ISSUE TITLE
从别的窗口切换回VSCode，焦点没有落在之前的编辑处

### ISSUE THREAD

**Issue by cdslily** [cweijan/vscode-office#61]

**Comment by cweijan** [comment]
你有没有升级扩展, 之前已经修复这个了.

**Comment by cdslily** [comment]
当前版本为2.2.0,没有可扩展更新。
![image](https://user-images.githubusercontent.com/17878363/152933902-5440a598-0a03-4cb2-a39e-89a29b8c2a60.png)

**Comment by cweijan** [comment]
安装这个呢. typora卸载掉
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office

**Comment by cdslily** [comment]
OK!
