### ISSUE TITLE
能否将 Vditor 版本升级到至少 3.8.5？

### ISSUE THREAD

**Issue by SiskonEmilia** [cweijan/vscode-office#64]
在 Vditor 3.8.5 版本中修复的严重问题：https://github.com/88250/lute/issues/149
此问题在之前的版本中导致在英文中的部分文字加粗无法正常使用空格，很影响使用。即：
a **word**
会变成
a**word**
希望能尽快解决此问题，万分感谢。

**Comment by cweijan** [comment]
这个问题我很久前就修复了, 你试下这个, 可能你安装的是typora.
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office

**Comment by SiskonEmilia** [comment]
非常感谢！发自我的华为手机-------- 原始邮件 --------发件人： WeiJian Chen ***@***.***>日期： 2022年2月23日周三 13:40收件人： cweijan/vscode-office ***@***.***>抄送： Siskon ***@***.***>, Author ***@***.***>主    题： Re: [cweijan/vscode-office] 能否将 Vditor 版本升级到至少 3.8.5？ (Issue #64)

这个问题我很久前就修复了, 你试下这个, 可能你安装的是typora.

https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office

**Comment by zhaoqingqing** [comment]
> 这个问题我很久前就修复了, 你试下这个, 可能你安装的是typora. https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office

@cweijan 还有typora的版本？我看分支有个typora

**Comment by cweijan** [comment]
@zhaoqingqing 引流用的, 功能一样
