### ISSUE TITLE
按钮图标消失

### ISSUE THREAD

**Issue by DingYizhi** [cweijan/vscode-office#67]
![UpChat20220304105710](https://user-images.githubusercontent.com/59859800/156696645-892c576d-b55b-41f0-8e42-16c7b92816b8.jpg)
上面一排按钮，点击依然有用，但图标消失，切换过颜色主题，都不行
vscode和插件均为最新版

**Comment by cweijan** [comment]
是这个插件吗
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office

**Comment by Ghr07h** [comment]
是的，我也出现了同样的情况，至少去年10月份左右图标是正常的，而且打开markdown文件时会加载很长一段时间，哪怕是一个很小的markdown文件，我怀疑是不是新版本有什么错误。
![image](https://user-images.githubusercontent.com/49585390/157654482-2995ea30-7aa4-4ac9-b667-639f1e101442.png)

**Comment by Ghr07h** [comment]
我安装了旧版本的插件，cweijan.vscode-office-2.5.1，现在一切正常了
![image](https://user-images.githubusercontent.com/49585390/157655018-88acc94e-405c-4779-a422-1cb196822084.png)

**Comment by fry404006308** [comment]
我也遇到了一样的情况

**Comment by fry404006308** [comment]
![image](https://user-images.githubusercontent.com/33335064/157770761-c55f6322-ae5d-4f90-a8aa-d670c5376fe2.png)
更新到老版本问题也不能解决

**Comment by cweijan** [comment]
Hi, 这是由于国内网络问题, 资源文件加载不出来, 最新的2.5.5版本将这关键资源改为本地加载了, 可以正常显示.
