### ISSUE TITLE
修改代码主题

### ISSUE THREAD

**Issue by Arrkwen** [cweijan/vscode-office#69]
大佬您好，请问可以修改一下代码主题吗。目前浅灰色的背景加上黑色字体，如果代码不高亮，很难看清楚代码。一般的经验，如果在白色内容主题下，代码背景是黑色，字体是白色，可以看的更清楚。我本来想在插件的代码中修改，但奈何找不到对应的css，如果大佬不想更新，可以告知我代码块对应的css,我自行更改也可，谢谢您

**Comment by cweijan** [comment]
发布了2.5.7版本, 对代码主题进行了优化
