### ISSUE TITLE
能否加上字数统计和样式修改

### ISSUE THREAD

**Issue by jxjxjhjh** [cweijan/vscode-office#7]
MD编辑器的字数统计一般都是刚需。
样式修改是希望能增加字体、字号、行高等基本属性，现在字数多了看起来费眼。

**Comment by cweijan** [comment]
1.7.7加上了字数统计, 样式我没计划调整, 你前端比较6的话可以尝试实现他.

**Comment by jxjxjhjh** [comment]
> 1.7.7加上了字数统计, 样式我没计划调整, 你前端比较6的话可以尝试实现他.

我会CSS，可是我不知道要怎么修改啊，VSCODE用得还不太懂
