### ISSUE TITLE
Add ods files to compatible files

### ISSUE THREAD

**Issue by simchanu29** [cweijan/vscode-office#7]
Since sheetjs seems to be able to open `.ods` files, it would be great if `.ods` files (from LibreOffice) were added to compatble files.

I can make a PR. I think the code needs to be modified here :  https://github.com/cweijan/vscode-office/blob/master/src/provider/officeViewerProvider.ts#L50-L52

Is it the only place the code needs to be modified ?
I tried this modification on my PC and it seems to work well.

On a sidenote, i tried this kind of modification with `.odt` files but unfortunately with no luck.

**Comment by cweijan** [comment]
Can you provide me a `ods` document?

**Comment by simchanu29** [comment]
You can find a sample file here : https://filebin.net/4hs95p8vg9nz7xkn (the link is up for 1 week)
Its a sheet file from LibreOffice.

You can find other sample files here as well.
https://help.libreoffice.org/latest/sq/text/scalc/06/calcsamplefiles.html

**Comment by cweijan** [comment]
Support at version 2.0.6.
