### ISSUE TITLE
请问如何修改保持图片的路径

### ISSUE THREAD

**Issue by lovebai** [cweijan/vscode-office#70]
我想修改一下复制图片的保持路径，我修改了vditor目录下的index.js文件没有用
```
url: '/',
accept: '/*',
```

**Comment by cweijan** [comment]
是在代码内定义的, 目前不支持自定义.
https://github.com/cweijan/vscode-office/blob/7b52c462e2ebbc2035c0fb82eb7b3bde1535c94b/src/provider/officeEditorProvider.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L103
https://github.com/cweijan/vscode-office/blob/7b52c462e2ebbc2035c0fb82eb7b3bde1535c94b/src/service/markdownService.ts#L84

**Comment by lovebai** [comment]
> 是在代码内定义的, 目前不支持自定义.
> 
> https://github.com/cweijan/vscode-office/blob/7b52c462e2ebbc2035c0fb82eb7b3bde1535c94b/src/provider/officeEditorProvider.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L103
> 
> 
> https://github.com/cweijan/vscode-office/blob/7b52c462e2ebbc2035c0fb82eb7b3bde1535c94b/src/service/markdownService.ts#L84

感谢回复，我知道怎么弄了

**Comment by LYwyc** [comment]
> > 是在代码内定义的, 目前不支持自定义.
> > https://github.com/cweijan/vscode-office/blob/7b52c462e2ebbc2035c0fb82eb7b3bde1535c94b/src/provider/officeEditorProvider.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L103
> > 
> > https://github.com/cweijan/vscode-office/blob/7b52c462e2ebbc2035c0fb82eb7b3bde1535c94b/src/service/markdownService.ts#L84
> 
> 感谢回复，我知道怎么弄了

您好，请问下怎么弄，我也遇到了相同的问题

**Comment by cweijan** [comment]
发布了2.5.5版本, 现在可以设置下图片路径.
![image](https://user-images.githubusercontent.com/27798227/170769238-79e27375-c71a-49a1-8fa5-adad477c758d.png)

**Comment by LYwyc** [comment]
> 发布了2.5.5版本, 现在可以设置下图片路径. ![image](https://user-images.githubusercontent.com/27798227/170769238-79e27375-c71a-49a1-8fa5-adad477c758d.png)

万分感谢！

**Comment by lovebai** [comment]
> 发布了2.5.5版本, 现在可以设置下图片路径. ![image](https://user-images.githubusercontent.com/27798227/170769238-79e27375-c71a-49a1-8fa5-adad477c758d.png)

感谢感谢
