### ISSUE TITLE
 修改截图粘贴时的默认路径

### ISSUE THREAD

**Issue by yiqieazy** [cweijan/vscode-office#71]
我在看了之前别人的问题后，
克隆了仓库里的代码，并修改了路径。
然后，请问怎么把代码打包成插件安装包，安装到VSCODE里。

或者说：请问有没有什么好的办法，把截图粘贴时的默认路径改成：在当前目录下生成一个  与当前编辑文件同名（且加上"_image_mk"后辍）的目录

**Comment by yiqieazy** [comment]
![image](https://user-images.githubusercontent.com/94970070/160414370-ea2a11ad-933a-4c63-b1e1-52ca30f4fdb0.png)
![image](https://user-images.githubusercontent.com/94970070/160414547-aa8cd799-f087-4690-abdf-fd643ad5220c.png)
因为本地安装目录里面没有找到src目录，就克隆了仓库里的代码来改了，却不知道怎么使用。
有会的大佬，麻烦教亿下，谢谢啦~

**Comment by cweijan** [comment]
发布了2.5.5版本, 现在可以设置下图片路径.
![image](https://user-images.githubusercontent.com/27798227/170769238-79e27375-c71a-49a1-8fa5-adad477c758d.png)
