### ISSUE TITLE
Some items related to sidebar background-color in viewer.css should be fixed 

### ISSUE THREAD

**Issue by MasouShizuka** [cweijan/vscode-office#73]
In `resource\pdf\viewer.css`, `background-color: #F7F7F7` is used in the sidebar related places, which causes the sidebar in pdf to still appear white in dark mode.
![image](https://user-images.githubusercontent.com/44764707/160760922-f504cd1b-f535-4b8e-a153-252ac35f3032.png)

Maybe these should be modified to `background-color: var(--sidebar-bg-color)`.
![image](https://user-images.githubusercontent.com/44764707/160761203-dcdcc57b-bdbc-4ad9-a2d4-b242df70e69f.png)

**Comment by cweijan** [comment]
This issue has been fixed.
