### ISSUE TITLE
markdown下无法输入独行latex公式的问题

### ISSUE THREAD

**Issue by Objia** [cweijan/vscode-office#77]
在markdown中编辑latex数学公式时，输入'$'符号会默认生成行内数学公式，即使输入两个'$'字符，仍然生成的是行内公式，而无法生成独行的数学公式。但是在vditor中测试时，不会出现该问题。目前只能通过使用vscode的编辑器手动修改markdown文本才能解决。我不太清楚这是一个bug问题，还是输入方式不对的问题。

**Comment by cweijan** [comment]
Hi, 发布了2.6.7版本修复了这个问题.
