### ISSUE TITLE
工具栏不显示，代码高亮语法无效

### ISSUE THREAD

**Issue by yanyu2015** [cweijan/vscode-office#79]
可能是因为vscode更新了
![image](https://user-images.githubusercontent.com/11142054/168585837-49788094-0d7d-4c29-bb78-78c23e61de44.png)
现在的工具栏如图，这个bug有点难受啊

**Comment by leo-mao** [comment]
相同情况
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by BlackCattt9** [comment]
原来不止我一人出现这个情况，看着可难受了
![image](https://user-images.githubusercontent.com/48442986/169475262-197b4a28-f226-4789-ba82-51b3d41dee1e.png)

**Comment by rayenyang** [comment]
+1

**Comment by cweijan** [comment]
最近国内网络有问题, 这个文件加载不出来, 等我给他改成静态的.
https://cdn.jsdelivr.net/npm/vditor@3.8.4/dist/js/icons/ant.js

**Comment by cweijan** [comment]
发布了2.5.5版本, 现在即使没有网络也可以正常使用了.
