### ISSUE TITLE
doesn't handle encoding for csv-files

### ISSUE THREAD

**Issue by ccoenen** [cweijan/vscode-office#8]
When working with a utf-8 encoded csv file, the editor will interpret it as ASCII and display this:
![grafik](https://user-images.githubusercontent.com/124909/114324560-16011200-9b2b-11eb-9ab8-2eefc61e5bb4.png)

**Comment by ccoenen** [comment]
I am aware that csv files are too simple to formally declare their encoding, but it would be useful to at least be able to choose the encoding somewhere. Ideally, though, the table view would guess the encoding, in the same way the text editor does. Or, in 2021, default to utf-8.

**Comment by ccoenen** [comment]
Interestingly: if I open an empty csv file, paste stuff in there and save the file, it will correctly write utf-8 to disk. But when I re-open the same file I just successfully saved, it will look like the screenshot above, i.e. utf-8 interpreted as ascii.

If I then continue to change the file and save it again, it will end up as broken text on disk that is no longer utf-8:
![grafik](https://user-images.githubusercontent.com/124909/114324700-d1c24180-9b2b-11eb-909f-f281220ee55a.png)

**Comment by cweijan** [comment]
Flow below two step.
![image](https://user-images.githubusercontent.com/27798227/114684536-94380100-9d43-11eb-916b-f8483f9a3c9a.png)
![image](https://user-images.githubusercontent.com/27798227/114684549-98fcb500-9d43-11eb-829f-54fd85f7c8d4.png)
