### ISSUE TITLE
一些bug：工具栏不显示，公式无法渲染

### ISSUE THREAD

**Issue by BlackCattt9** [cweijan/vscode-office#80]
vscode：2021 version1.61
office viewer：2.5.4，
但是打开后 ：
1、上方图标显示有问题，除了编辑和转为pdf两个图标，其余图标不显示，2、对公式不渲染；

![image](https://user-images.githubusercontent.com/48442986/169500753-125532c5-7d19-4871-9570-d9549c9d4ef8.png)

开始以为是不兼容的问题，然后：
把office viewer回退到版本2.1.1，发现打开md文件后无显示
又把office viewer回退到1.9.1，发现是能正常显示的，公式也是能正常渲染的，这个时候是没有用vditor的
不知道是否与vditor的使用有关？
可是同样的文本，使用思源软件（也是vditor），渲染结果也是正常的

**Comment by Esdrin** [comment]
最近我的也有这个问题，版本2.5.4，并且打开Markdown文件速度也突然慢了很多
![image](https://user-images.githubusercontent.com/97580517/170199285-5e0ad92f-4491-4512-a804-c7dff387af2a.png)

**Comment by Esdrin** [comment]
晚上莫名其妙好了？离谱

**Comment by CybCom** [comment]
工具栏问题同样存在，而且重装无法解决

**Comment by Esdrin** [comment]
我也不知道我怎么好的，反正啥也没改突然间就好了

**Comment by cweijan** [comment]
发布了2.5.5版本进行优化, 现在主要资源使用静态加载.

**Comment by Esdrin** [comment]
好耶

**Comment by CybCom** [comment]
已经解决，试了几个情况效果都不错，感谢。也许可以close了？
