### ISSUE TITLE
建议加入字数统计

### ISSUE THREAD

**Issue by CybCom** [cweijan/vscode-office#82]
编辑器页面与现有的字数统计插件都不很兼容，加入Typora那样的词数、段落统计似乎能方便一点。

**Comment by cweijan** [comment]
右下角的状态栏有字数统计, 保存后更新.

**Comment by zhaoqingqing** [comment]
插个眼：保存一下就会显示当前文档的字数，只是打开不按保存还是上次的。

**Comment by CybCom** [comment]
我也是这个意思
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "qingqing.zhao"; 
Date: 2022年9月16日(星期五) 中午11:22
To: "cweijan/vscode-office"; 
Cc: "CybCom"; "Author"; 
Subject: Re: [cweijan/vscode-office] 建议加入字数统计 (Issue #82)

&nbsp;


 
插个眼：保存一下就会显示当前文档的字数，只是打开不按保存还是上次的。

**Comment by cweijan** [comment]
发布了2.7.4修复
