### ISSUE TITLE
markdown下图片跳转链接点击无反应

### ISSUE THREAD

**Issue by rayenyang** [cweijan/vscode-office#83]
例如：
```
[![img](https://github.githubassets.com/images/modules/marketplace/marketplace-illustration-01.svg)](https://github.com/marketplace)
```

效果如下：
[![img](https://github.githubassets.com/images/modules/marketplace/marketplace-illustration-01.svg)](https://github.com/marketplace)

点击图片可以跳转到 `https://github.com/marketplace`，在此插件则无法跳转

**Comment by cweijan** [comment]
在最新发布的2.5.8版本支持了, 双击或者ctrl+单击.

**Comment by rayenyang** [comment]
@cweijan 网络链接可以了，但如果链接是本地文件，例如a.txt，会变成用浏览器打开`https://file+.vscode-resource.vscode-cdn.net/a.txt`，vscode默认markdown预览中是直接用vscode打开a.txt，这样会比较合理

**Comment by cweijan** [comment]
尝试2.6.1版本, 修复了这个问题.

**Comment by rayenyang** [comment]
@cweijan 十分感谢对此功能的关注！但更新到最新版之后，和预期有些出入。
我这边装了[mindmap](https://marketplace.visualstudio.com/items?itemName=eightHundreds.vscode-mindmap)和[drawio](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio)的插件使得可以在markdown直接嵌入脑图和各种流程图。例如：
* 新建a.png，用vscode打开的话是通过drawio的插件打开一个绘图面板tab （ `[![](a.png)](a.png)` ）
* 新建b.km.svg是用mindmap的插件打开绘图面板tab

在默认的markdown预览器或者[Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)这个预览插件都能实现以上操作。

若在Office viewer打开的话，a.png会报错（不能用文本编辑器打开二进制文件），而b.km.svg是一片空白。

**Comment by cweijan** [comment]
我发布2.6.2支持了， 上个版本是只支持打开相对路径的markdown
