### ISSUE TITLE
焦点问题

### ISSUE THREAD

**Issue by bcqsd** [cweijan/vscode-office#87]
windows，在应用之间切换，经常焦点闪一下就消失。（偶尔切换两次能找到焦点）
edit in vscode可以每次都找到焦点，但是编辑的时候左边的视图会变动，跳到并非编辑的地方。
还有原生的按alt会把焦点转移到工具栏，再按alt会回到编辑位置。但是插件下的md按两次alt焦点回不来

**Comment by cweijan** [comment]
在设置中加下这个设置.
```json
{
"window.customMenuBarAltFocus": false
}
```

**Comment by bcqsd** [comment]
> 在设置中加下这个设置.
> 
> ```json
> {
> "window.customMenuBarAltFocus": false
> }
> ```

这样只是禁用了alt，但我希望按两次alt能够让焦点从工具栏回到文本编辑上。
另外这只是意外发现，最主要的还是切换应用无法每次都获取焦点，但是连续切换两次可以获取到，是我的特殊情况吗。
我是用alt+tab切换的，会不会和这个有关系。而且无论是否禁用alt，切换应用之后的焦点问题都存在
另外，刚刚用鼠标获取焦点，也是会闪一下然后失败
点击其他应用->点击md文本->点击其他应用->点击md文本
四次操作中，两次点击md文本只有一次能成功激活焦点

**Comment by cweijan** [comment]
这是vscode的问题, 自定义编辑器不同于内置编辑器, 它是一个ifame, 在早期的vscode是会让iframe重新获得焦点的, 但现在不会了, 现在唯一解决的方法就是禁用alt触发菜单.

**Comment by bcqsd** [comment]
好的，谢谢回复！
