### ISSUE TITLE
vscode无法正确打开内部文件链接

### ISSUE THREAD

**Issue by canbefree** [cweijan/vscode-office#89]
问题描述:
markdown格式下： 

[文件](./git.md) 

ctrl+右键点击打开的是网站： https://file+.vscode-resource.vscode-cdn.net/[filepath]/git.md

希望结果： 
使用 vscode tab窗口打开文件

操作系统: window 10 

插件版本： 2.6.0

**Comment by cweijan** [comment]
Hi, 我已经发布2.6.1修复了, 其实以前是做过处理的, 新版本vscode内部资源路径变了.
