### ISSUE TITLE
安装vscode-office 之后，markdown preview 会强制更改为白色

### ISSUE THREAD

**Issue by heartacker** [cweijan/vscode-office#9]
![image](https://user-images.githubusercontent.com/1876302/114329605-5cc62a80-9b72-11eb-91c5-4d5e6fe678b4.png)

禁用后符合vscode的主题色。

vscode-office的设置好像没有一个是可以更改整个变化的。

**Comment by cweijan** [comment]
版本2.0.4移除了该样式.
