### ISSUE TITLE
cannot use pandoc to render markdown file when this extension is active

### ISSUE THREAD

**Issue by zkwabm** [cweijan/vscode-office#9]
The markdown file cannot be rendered by pandoc extension when this extension is active.

The error information is as follow：

Command 'Pandoc Render' resulted in an error (Running the contributed command: 'pandoc.render' failed.)

When this extension is disabled, pandoc render works fine.

**Comment by cweijan** [comment]
Right click markdown, then:
![image](https://user-images.githubusercontent.com/27798227/100188190-a6480d00-2f24-11eb-9f54-ff09699085eb.png)


![image](https://user-images.githubusercontent.com/27798227/100188146-8f091f80-2f24-11eb-86e1-2e6657975a93.png)

**Comment by zkwabm** [comment]
Yes, it works. Thanks！
