### ISSUE TITLE
默认的markdown不支持div颜色设置了，以前支持的，望加上，拜谢拜谢

### ISSUE THREAD

**Issue by fry404006308** [cweijan/vscode-office#93]
# 一、不支持div颜色了

![image](https://user-images.githubusercontent.com/33335064/174958411-f1d30b7f-684f-45be-9bc1-9da667f4e81a.png)

以前这种div的颜色是支持的，office viewer版本更新后就不支持了

# 二、typora本身也是支持的

![image](https://user-images.githubusercontent.com/33335064/174958665-722b3d7a-562e-4f58-9b63-858c83a1339d.png)

typora本身也是支持这个div颜色的

# 三、markdown中的颜色标注还是蛮重要的

markdown中的颜色标注还是蛮重要的，这样可以帮助我们轻松发现文字重点

大幅节约阅读markdown的时间

其实这和深度学习里面的注意力机制是一回事

# 四、拜谢拜谢

我一直在用作者的产品，挺好用

拜谢作者，奥利给

**Comment by cweijan** [comment]
是因为最近的版本强制上了主题色, 这里也被影响到了, 你可以先暂时屏蔽主题色, 我看怎么修复它
![image](https://user-images.githubusercontent.com/27798227/174997713-ca900497-4d7d-476c-bd07-276f7564c164.png)

**Comment by fry404006308** [comment]
问题解决，拜谢拜谢

**Comment by fry404006308** [comment]
您好，我是范仁义，您的邮件我已经收到，我会尽快处理，谢谢。
