### ISSUE TITLE
无法查看 svg 文件，因为背景是黑色的，而 svg 本身就是黑色的

### ISSUE THREAD

**Issue by hzh-test** [cweijan/vscode-office#94]

**Comment by cweijan** [comment]
我发布了2.6.4版本, 将背景改为灰色.

**Comment by hzh-test** [comment]
哇，速度这么快！

有点敷衍啊！这个灰色也太黑了，只能隐约看见图标，在画廊中完全看不出来。

要不特殊处理一下，搞成白色的？

**Comment by cweijan** [comment]
因为我之前疑惑为啥有些svg显示不出来, 你这反馈让我知道了, 就立刻改了, 我这里显示效果还是挺好的, 改成白色太亮了, 不好看.
![image](https://user-images.githubusercontent.com/27798227/176136182-7b12803c-4ae8-4ed0-b35b-decc12983a2d.png)

**Comment by hzh-test** [comment]
我觉得把背景改成斑纹可已很容易区分出透明，市面上一般都是这么高的，我已经提交 pull requests 了，你试试可不可行，我是直接在 VSCode 的开发者模式下调试的，代码没试过，没时间搞，请作者编译后试试，没问题就合并一下，第一次提交 pull request 还有点小激动。

**Comment by hzh-test** [comment]
效果如下：
<img width="1172" alt="iShot2022-06-28 17 10 36" src="https://user-images.githubusercontent.com/32761288/176141277-5f50a7bd-6824-4a84-a6d4-b99e6ccdc07e.png">
<img width="1172" alt="iShot2022-06-28 17 10 29" src="https://user-images.githubusercontent.com/32761288/176141323-7f9e7b46-7e18-4e58-9eb1-59050688b39c.png">

**Comment by cweijan** [comment]
试了下, 太亮了, 我vscode用的黑主题.

**Comment by hzh-test** [comment]
难怪，看来你得搞个暗黑和非暗黑主题的设置功能，不过这个看起来工作量很大

**Comment by hzh-test** [comment]
这种如何？
![image](https://user-images.githubusercontent.com/32761288/176146777-4293b4a5-35f0-4d07-a220-0943125fdb6c.png)

**Comment by hzh-test** [comment]
![image](https://user-images.githubusercontent.com/32761288/176147864-57c9a56a-0245-422e-ba33-79ae45387166.png)

**Comment by hzh-test** [comment]
求解决，我说说我是怎么做的，直接用画图工具画一个白黑方格，再转化为base64，如下：
![image](https://user-images.githubusercontent.com/32761288/176148212-2773c7c6-7aa6-41c8-93d3-4e58cdb1edda.png)
在线base64 转化：https://tool.chinaz.com/tools/imgtobase
你调节一下颜色就ok了，或者你说两个颜色给我，我来画。

**Comment by hzh-test** [comment]
咦，看久了，发现现在这样也挺好的，不过你有一个地方忘改了，我补充了一下，已提交 pull request。

**Comment by cweijan** [comment]
好, 谢谢你的贡献

**Comment by cweijan** [comment]
vscode css是可以设置不同主题用不同样式的, 你看我最新的提交

**Comment by hzh-test** [comment]
噢，这个不错。

不过你是不是又只改了一个，.lg-outer .lg-thumb-item {} 也要区分主题吧

**Comment by cweijan** [comment]
改好发布2.6.5了
















在 2022-06-28 18:58:58，"胡镇华" ***@***.***> 写道：

噢，这个不错。

不过你是不是又只改了一个，.lg-outer .lg-thumb-item {} 也要区分主题吧

**Comment by hzh-test** [comment]
看到了，Very Good！

再提个建议，顶部工具栏可以想 markdown 工具栏那样，加多个编辑按钮，点击之后可打开原始页面，直接编辑 svg。
